In [1]:
# Day 20 - Step 1
# Install required libraries

!pip install -q langchain-text-splitters
!pip install -q langchain-community
!pip install -q langchain-huggingface
!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q fastapi uvicorn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 41.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 61.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 7.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 65.0 MB/s eta 0:00:00

In [2]:
import requests
print(requests.__version__)

2.34.2

In [3]:
# Day 20 - Step 2
# Required imports

import os
import time
import json

from typing import List, Dict, Any

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

print("All imports loaded successfully!")

All imports loaded successfully!

/tmp/ipykernel_667/472579479.py:12: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS

In [4]:
# Day 20 - Step 3
# Chunking pipeline from Day 12

document = """
Paste your Day 12 document text here.
"""

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = text_splitter.split_text(document)

print("Total chunks:", len(chunks))
print("\nFirst chunk:\n")
print(chunks[0] if chunks else "No chunks created")

Total chunks: 1

First chunk:

Paste your Day 12 document text here.

In [5]:
# Day 20 - Step 3
# Day 12 document + chunking pipeline

document = """
Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making. Artificial
intelligence has become an important technology because computers can process
large amounts of information quickly and identify useful patterns in data.

The development of artificial intelligence involves several important areas.
Machine learning is one of the major areas of AI. Machine learning allows a
computer system to learn patterns from data rather than being explicitly
programmed for every individual task. A machine learning model is trained using
data and can later make predictions or decisions based on new information.
The quality and quantity of training data can strongly affect model performance.

Supervised learning is a machine learning approach that uses labeled data.
During training, the model receives examples where the expected output is known.
The model learns a relationship between input features and output labels.
Classification and regression are two common supervised learning tasks.
Classification predicts categories such as spam or not spam, while regression
predicts numerical values such as prices, temperature, or sales.

Unsupervised learning works with data where predefined output labels are not
available. The purpose is often to discover hidden patterns or structures.
Clustering is a common unsupervised learning technique. It groups similar
data points together according to their characteristics. Unsupervised learning
can be useful for customer segmentation, exploratory data analysis, and finding
relationships that may not be obvious in a dataset.

Reinforcement learning is another important machine learning approach. In this
method, an agent interacts with an environment and learns through feedback.
The agent receives rewards for useful actions and may receive negative feedback
for undesirable actions. Over time, the system learns a strategy for selecting
actions. Reinforcement learning has applications in robotics, games, resource
management, and some decision-making systems.

Deep learning is a branch of machine learning based on artificial neural
networks. Deep learning models contain multiple layers that can learn complex
representations from data. They are particularly useful when large datasets
and significant computing resources are available. Deep learning has contributed
to advances in image recognition, speech recognition, natural language processing,
recommendation systems, and many other applications.

Natural Language Processing, commonly called NLP, focuses on enabling computers
to work with human language. NLP systems can process written or spoken language
and perform tasks such as translation, sentiment analysis, question answering,
text classification, summarization, and chatbot interaction. Modern NLP systems
use machine learning and deep learning techniques to understand relationships
between words and larger pieces of text.

Computer vision is an area of artificial intelligence that deals with images
and videos. Computer vision systems can identify objects, recognize patterns,
analyze scenes, and extract useful information from visual data. Applications
include medical image analysis, object detection, quality inspection,
autonomous systems, security applications, and image classification.

Generative AI is a rapidly developing area of artificial intelligence.
Generative systems can create new content such as text, images, audio, code,
and other forms of media. Large language models are an important example of
generative AI technology. These systems learn statistical patterns from large
datasets and can generate responses based on user instructions. Generative AI
is being explored for education, software development, content creation,
research assistance, customer support, and productivity.

Artificial intelligence has applications across many industries. In healthcare,
AI can assist with medical image analysis, clinical decision support, research,
and administrative tasks. In education, AI can support personalized learning,
automated feedback, and educational content generation. In finance, AI can be
used for fraud detection, risk analysis, forecasting, and customer services.
In manufacturing, AI can support quality control, predictive maintenance,
production planning, and automation.

Transportation is another important application area. AI can help analyze
traffic conditions, optimize routes, support driver assistance systems, and
improve transportation planning. In retail and e-commerce, AI can be used for
recommendation systems, demand forecasting, customer analysis, and inventory
management. Entertainment platforms also use AI techniques to recommend
movies, music, videos, and other content based on user interactions.

Data plays an important role in the development of AI systems. Before training
a machine learning model, data often needs to be collected, cleaned, transformed,
and analyzed. Missing values, duplicate records, inconsistent formats, and
incorrect information can reduce the quality of a dataset. Data preprocessing
helps prepare information for reliable analysis and model training.

Evaluation is an essential part of machine learning and artificial intelligence.
Different tasks require different evaluation measures. Classification models
may be evaluated using accuracy, precision, recall, and F1 score. Regression
models can be evaluated using measures such as mean absolute error and mean
squared error. Evaluation helps researchers and developers understand how well
a system performs and whether it is suitable for a particular application.

Despite its benefits, artificial intelligence creates important challenges.
AI systems can produce biased results when training data contains bias.
Privacy is another concern because AI applications may process large amounts
of personal or sensitive information. Security, transparency, reliability,
and accountability are also important considerations when developing and
deploying intelligent systems.

Responsible AI focuses on developing systems that are useful, reliable, safe,
transparent, and fair. Organizations need to consider how AI systems are
trained, evaluated, monitored, and used. Human oversight can be important,
especially when AI systems are used in situations where decisions can have
significant consequences.

The future of artificial intelligence is expected to involve continued research
in language understanding, computer vision, robotics, generative AI, and
intelligent decision support. Improvements in computing, algorithms, and data
may enable new applications. At the same time, researchers and organizations
will need to address technical, social, ethical, and security challenges.

Overall, artificial intelligence combines data, algorithms, computing resources,
and evaluation methods to create systems that can perform useful tasks.
Understanding different AI techniques and their applications is important for
students and professionals working with modern technology. Careful development,
testing, and responsible use can help ensure that AI systems provide useful
results while reducing potential risks.
"""

print("Total characters:", len(document))


# Recursive chunking
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = text_splitter.split_text(document)

print("Total chunks:", len(chunks))
print("\nFirst chunk:\n")
print(chunks[0])

Total characters: 7376
Total chunks: 19

First chunk:

Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making. Artificial
intelligence has become an important technology because computers can process
large amounts of information quickly and identify useful patterns in data.

In [6]:
from langchain_core.documents import Document
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

# Day 17 style metadata
documents = []

for i, chunk in enumerate(chunks):
    doc = Document(
        page_content=chunk,
        metadata={
            "source": "Day 12 AI Document",
            "category": "Artificial Intelligence",
            "document_type": "Technical",
            "chunk_id": i
        }
    )
    documents.append(doc)

print("Total LangChain documents:", len(documents))
print("\nFirst document metadata:")
print(documents[0].metadata)

# Day 14 embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Create embeddings
texts = [doc.page_content for doc in documents]

embeddings = model.encode(texts)
embeddings = np.array(embeddings, dtype="float32")

print("\nEmbedding shape:", embeddings.shape)

# Create FAISS index
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

print("FAISS index created successfully!")
print("Index size:", index.ntotal)

Total LangChain documents: 19

First document metadata:
{'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 0}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding shape: (19, 384)
FAISS index created successfully!
Index size: 19

In [7]:
def semantic_search(query, top_k=3):
    # Convert query into embedding
    query_embedding = model.encode([query])
    query_embedding = np.array(query_embedding, dtype="float32")

    # Search in FAISS
    distances, indices = index.search(query_embedding, top_k)

    results = []

    for distance, idx in zip(distances[0], indices[0]):
        doc = documents[idx]

        results.append({
            "document": doc,
            "score": float(distance)
        })

    return results


# Test search
query = "What is artificial intelligence?"

results = semantic_search(query, top_k=3)

for i, result in enumerate(results, 1):
    print(f"\nResult {i}")
    print("Score:", result["score"])
    print("Text:", result["document"].page_content[:300])
    print("Metadata:", result["document"].metadata)

Result 1
Score: 0.3212980031967163
Text: Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decis
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 0}

Result 2
Score: 0.6256104707717896
Text: Overall, artificial intelligence combines data, algorithms, computing resources,
and evaluation methods to create systems that can perform useful tasks.
Understanding different AI techniques and their applications is important for
students and professionals working with modern technology. Careful de
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 18}

Result 3
Score: 0.7437357306480408
Text: The development of artificial intelligence involves several important areas.
Machine learning is one of the major areas of AI. Machine learning allows a
computer system to learn patterns from data rather than being explicitly
programmed for every individual task. A machine learning model is trained
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 1}

In [9]:
def filtered_semantic_search(query, filters=None, top_k=3):
    filters = filters or {}

    # Pehle semantic search
    results = semantic_search(query, top_k=len(documents))

    filtered_results = []

    for result in results:
        doc = result["document"]
        metadata = doc.metadata

        # Category filter
        if "category" in filters:
            if metadata.get("category") != filters["category"]:
                continue

        # Document type filter
        if "document_type" in filters:
            if metadata.get("document_type") != filters["document_type"]:
                continue

        filtered_results.append(result)

    return filtered_results[:top_k]


# Test
query = "What is artificial intelligence?"

results = filtered_semantic_search(
    query,
    filters={
        "category": "Artificial Intelligence",
        "document_type": "Technical"
    },
    top_k=3
)

print("Filtered results:", len(results))

for i, result in enumerate(results, 1):
    print(f"\nResult {i}")
    print("Score:", result["score"])
    print("Text:", result["document"].page_content[:300])
    print("Metadata:", result["document"].metadata)

Filtered results: 3

Result 1
Score: 0.3212980031967163
Text: Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decis
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 0}

Result 2
Score: 0.6256104707717896
Text: Overall, artificial intelligence combines data, algorithms, computing resources,
and evaluation methods to create systems that can perform useful tasks.
Understanding different AI techniques and their applications is important for
students and professionals working with modern technology. Careful de
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 18}

Result 3
Score: 0.7437357306480408
Text: The development of artificial intelligence involves several important areas.
Machine learning is one of the major areas of AI. Machine learning allows a
computer system to learn patterns from data rather than being explicitly
programmed for every individual task. A machine learning model is trained
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 1}

In [10]:
def build_context(results):
    context_parts = []

    for i, result in enumerate(results, 1):
        doc = result["document"]

        context_parts.append(
            f"Source {i}:\n"
            f"{doc.page_content}\n"
            f"Metadata: {doc.metadata}\n"
        )

    return "\n".join(context_parts)


# Test
query = "What is artificial intelligence?"

results = filtered_semantic_search(
    query,
    filters={
        "category": "Artificial Intelligence",
        "document_type": "Technical"
    },
    top_k=3
)

context = build_context(results)

print("Context created successfully!")
print("\n" + context[:2000])

Context created successfully!

Source 1:
Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making. Artificial
intelligence has become an important technology because computers can process
large amounts of information quickly and identify useful patterns in data.
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 0}

Source 2:
Overall, artificial intelligence combines data, algorithms, computing resources,
and evaluation methods to create systems that can perform useful tasks.
Understanding different AI techniques and their applications is important for
students and professionals working with modern technology. Careful development,
testing, and responsible use can help ensure that AI systems provide useful
results while reducing potential risks.
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 18}

Source 3:
The development of artificial intelligence involves several important areas.
Machine learning is one of the major areas of AI. Machine learning allows a
computer system to learn patterns from data rather than being explicitly
programmed for every individual task. A machine learning model is trained using
data and can later make predictions or decisions based on new information.
The quality and quantity of training data can strongly affect model performance.
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 1}

In [11]:
def build_grounded_prompt(query, context):

    prompt = f"""
You are a helpful AI knowledge assistant.

Answer the user's question using ONLY the provided context.

If the answer is not available in the context, clearly say:
"I don't have enough information in the provided context."

Do not make up facts or use outside information.

User Question:
{query}

Retrieved Context:
{context}

Answer:
"""

    return prompt


# Test
query = "What is artificial intelligence?"

grounded_prompt = build_grounded_prompt(
    query,
    context
)

print(grounded_prompt[:3000])

You are a helpful AI knowledge assistant.

Answer the user's question using ONLY the provided context.

If the answer is not available in the context, clearly say:
"I don't have enough information in the provided context."

Do not make up facts or use outside information.

User Question:
What is artificial intelligence?

Retrieved Context:
Source 1:
Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making. Artificial
intelligence has become an important technology because computers can process
large amounts of information quickly and identify useful patterns in data.
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 0}

Source 2:
Overall, artificial intelligence combines data, algorithms, computing resources,
and evaluation methods to create systems that can perform useful tasks.
Understanding different AI techniques and their applications is important for
students and professionals working with modern technology. Careful development,
testing, and responsible use can help ensure that AI systems provide useful
results while reducing potential risks.
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 18}

Source 3:
The development of artificial intelligence involves several important areas.
Machine learning is one of the major areas of AI. Machine learning allows a
computer system to learn patterns from data rather than being explicitly
programmed for every individual task. A machine learning model is trained using
data and can later make predictions or decisions based on new information.
The quality and quantity of training data can strongly affect model performance.
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 1}


Answer:

In [12]:
def retrieve_context(query, filters=None, top_k=3):
    results = filtered_semantic_search(
        query,
        filters=filters,
        top_k=top_k
    )

    context = build_context(results)

    return context, results


# Test
query = "What is machine learning?"

context, results = retrieve_context(
    query,
    filters={
        "category": "Artificial Intelligence",
        "document_type": "Technical"
    },
    top_k=3
)

print("RAG retrieval completed successfully!")
print("Retrieved documents:", len(results))

print("\nContext Preview:\n")
print(context[:2000])

RAG retrieval completed successfully!
Retrieved documents: 3

Context Preview:

Source 1:
The development of artificial intelligence involves several important areas.
Machine learning is one of the major areas of AI. Machine learning allows a
computer system to learn patterns from data rather than being explicitly
programmed for every individual task. A machine learning model is trained using
data and can later make predictions or decisions based on new information.
The quality and quantity of training data can strongly affect model performance.
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 1}

Source 2:
Supervised learning is a machine learning approach that uses labeled data.
During training, the model receives examples where the expected output is known.
The model learns a relationship between input features and output labels.
Classification and regression are two common supervised learning tasks.
Classification predicts categories such as spam or not spam, while regression
predicts numerical values such as prices, temperature, or sales.
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 2}

Source 3:
Evaluation is an essential part of machine learning and artificial intelligence.
Different tasks require different evaluation measures. Classification models
may be evaluated using accuracy, precision, recall, and F1 score. Regression
models can be evaluated using measures such as mean absolute error and mean
squared error. Evaluation helps researchers and developers understand how well
a system performs and whether it is suitable for a particular application.
Metadata: {'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 14}

In [13]:
def get_confidence_warning(results, threshold=0.3):
    if not results:
        return "LOW CONFIDENCE: No relevant information found."

    # FAISS L2 distance mein lower value = closer match
    best_distance = results[0]["score"]

    if best_distance > threshold:
        return "LOW CONFIDENCE: The retrieved information may not be sufficiently relevant."

    return "Confidence is acceptable."


# Test
warning = get_confidence_warning(results)

print(warning)

LOW CONFIDENCE: The retrieved information may not be sufficiently relevant.

In [14]:
def prepare_rag_response(query, filters=None, top_k=3):
    # Retrieve relevant documents
    context, results = retrieve_context(
        query,
        filters=filters,
        top_k=top_k
    )

    # Confidence warning
    confidence_message = get_confidence_warning(results)

    # Source citations
    sources = []

    for i, result in enumerate(results, 1):
        doc = result["document"]

        sources.append({
            "source_id": i,
            "source": doc.metadata.get("source"),
            "category": doc.metadata.get("category"),
            "document_type": doc.metadata.get("document_type"),
            "chunk_id": doc.metadata.get("chunk_id"),
            "score": result["score"]
        })

    return {
        "query": query,
        "context": context,
        "sources": sources,
        "confidence": confidence_message
    }


# Test
response_data = prepare_rag_response(
    "What is machine learning?",
    filters={
        "category": "Artificial Intelligence",
        "document_type": "Technical"
    },
    top_k=3
)

print("RAG response prepared successfully!")

print("\nConfidence:")
print(response_data["confidence"])

print("\nSources:")
for source in response_data["sources"]:
    print(source)

RAG response prepared successfully!

Confidence:
LOW CONFIDENCE: The retrieved information may not be sufficiently relevant.

Sources:
{'source_id': 1, 'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 1, 'score': 0.48326969146728516}
{'source_id': 2, 'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 2, 'score': 0.7471140623092651}
{'source_id': 3, 'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 14, 'score': 0.936577558517456}

In [15]:
def run_rag(query, filters=None, top_k=3):
    # 1. Retrieve relevant context
    context, results = retrieve_context(
        query,
        filters=filters,
        top_k=top_k
    )

    # 2. Build grounded prompt
    prompt = build_grounded_prompt(
        query,
        context
    )

    # 3. Prepare sources
    sources = []

    for i, result in enumerate(results, 1):
        doc = result["document"]

        sources.append({
            "source_id": i,
            "source": doc.metadata.get("source"),
            "category": doc.metadata.get("category"),
            "document_type": doc.metadata.get("document_type"),
            "chunk_id": doc.metadata.get("chunk_id"),
            "score": result["score"]
        })

    # 4. Confidence information
    confidence = get_confidence_warning(results)

    return {
        "query": query,
        "prompt": prompt,
        "sources": sources,
        "confidence": confidence
    }


# Test
rag_result = run_rag(
    "What is artificial intelligence?",
    filters={
        "category": "Artificial Intelligence",
        "document_type": "Technical"
    },
    top_k=3
)

print("RAG pipeline working successfully!")

print("\nQuery:")
print(rag_result["query"])

print("\nConfidence:")
print(rag_result["confidence"])

print("\nSources:")
for source in rag_result["sources"]:
    print(source)

RAG pipeline working successfully!

Query:
What is artificial intelligence?

Confidence:
LOW CONFIDENCE: The retrieved information may not be sufficiently relevant.

Sources:
{'source_id': 1, 'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 0, 'score': 0.3212980031967163}
{'source_id': 2, 'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 18, 'score': 0.6256104707717896}
{'source_id': 3, 'source': 'Day 12 AI Document', 'category': 'Artificial Intelligence', 'document_type': 'Technical', 'chunk_id': 1, 'score': 0.7437357306480408}

In [18]:
import os

print("GEMINI_API_KEY" in os.environ)

False

In [21]:
from google import genai
from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")

client = genai.Client(api_key=api_key)

print("Gemini client connected successfully!")

Gemini client connected successfully!

In [23]:
def generate_answer(query, filters=None, top_k=3):
    context, results = retrieve_context(
        query,
        filters=filters,
        top_k=top_k
    )

    prompt = build_grounded_prompt(query, context)

    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )

    return response.text, results


query = "What is artificial intelligence?"

answer, results = generate_answer(
    query,
    filters={
        "category": "Artificial Intelligence",
        "document_type": "Technical"
    },
    top_k=3
)

print("Answer:\n")
print(answer)

Answer:

Based on the provided context, Artificial Intelligence (AI) is a field of computer science focused on creating systems capable of performing tasks that normally require human intelligence. These tasks include:

* Learning
* Reasoning
* Problem solving
* Understanding language
* Recognizing images
* Making predictions
* Supporting decision making

Additionally, artificial intelligence combines data, algorithms, computing resources, and evaluation methods to create systems that can perform useful tasks.

In [24]:
import numpy as np

def get_confidence_warning(query, results, threshold=0.3):
    if not results:
        return "LOW CONFIDENCE: No relevant information found."

    query_embedding = model.encode([query])[0]
    query_embedding = np.array(query_embedding, dtype="float32")

    similarities = []

    for result in results:
        doc = result["document"]
        doc_embedding = model.encode([doc.page_content])[0]
        doc_embedding = np.array(doc_embedding, dtype="float32")

        cosine_similarity = np.dot(query_embedding, doc_embedding) / (
            np.linalg.norm(query_embedding) * np.linalg.norm(doc_embedding)
        )

        similarities.append(float(cosine_similarity))

    best_similarity = max(similarities)

    if best_similarity < threshold:
        return f"LOW CONFIDENCE: Similarity score is {best_similarity:.3f}"

    return f"Confidence acceptable: Similarity score is {best_similarity:.3f}"


query = "What is artificial intelligence?"

confidence = get_confidence_warning(query, results)

print(confidence)

Confidence acceptable: Similarity score is 0.839

In [25]:
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="AI Knowledge Assistant")


class AskRequest(BaseModel):
    query: str


@app.post("/ask")
def ask(request: AskRequest):
    answer, results = generate_answer(
        request.query,
        filters={
            "category": "Artificial Intelligence",
            "document_type": "Technical"
        },
        top_k=3
    )

    confidence = get_confidence_warning(
        request.query,
        results
    )

    sources = []

    for i, result in enumerate(results, 1):
        doc = result["document"]

        sources.append({
            "source_id": i,
            "source": doc.metadata.get("source"),
            "category": doc.metadata.get("category"),
            "document_type": doc.metadata.get("document_type"),
            "chunk_id": doc.metadata.get("chunk_id"),
            "score": result["score"]
        })

    return {
        "query": request.query,
        "answer": answer,
        "confidence": confidence,
        "sources": sources
    }


print("FastAPI app created successfully!")

FastAPI app created successfully!

In [29]:
import nest_asyncio
import uvicorn

nest_asyncio.apply()

config = uvicorn.Config(
    app,
    host="0.0.0.0",
    port=8000
)

server = uvicorn.Server(config)

await server.serve()

INFO:     Started server process [667]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [667]

In [30]:
import threading
import uvicorn

config = uvicorn.Config(
    app,
    host="0.0.0.0",
    port=8000
)

server = uvicorn.Server(config)

thread = threading.Thread(
    target=server.run,
    daemon=True
)

thread.start()

print("FastAPI server started successfully!")

INFO:     Started server process [667]

FastAPI server started successfully!

INFO:     Waiting for application startup.

In [32]:
import requests

response = requests.post(
    "http://127.0.0.1:8000/ask",
    json={
        "query": "What is artificial intelligence?"
    }
)

print("Status code:", response.status_code)
print("\nResponse:")
print(response.text)

INFO:     127.0.0.1:45324 - "POST /ask HTTP/1.1" 200 OK
Status code: 200

Response:
{"query":"What is artificial intelligence?","answer":"Based on the provided context, Artificial Intelligence is a field of computer science that focuses on creating systems capable of performing tasks that normally require human intelligence. These tasks include learning, reasoning, problem solving, understanding language, recognizing images, making predictions, and supporting decision making. \n\nAdditionally, it combines data, algorithms, computing resources, and evaluation methods to build systems that can perform useful tasks.","confidence":"Confidence acceptable: Similarity score is 0.839","sources":[{"source_id":1,"source":"Day 12 AI Document","category":"Artificial Intelligence","document_type":"Technical","chunk_id":0,"score":0.3212980031967163},{"source_id":2,"source":"Day 12 AI Document","category":"Artificial Intelligence","document_type":"Technical","chunk_id":18,"score":0.6256104707717896},{"source_id":3,"source":"Day 12 AI Document","category":"Artificial Intelligence","document_type":"Technical","chunk_id":1,"score":0.7437357306480408}]}

In [33]:
test_queries = [
    "What is artificial intelligence?",
    "What is machine learning?",
    "What is deep learning?",
    "What is natural language processing?",
    "What is computer vision?",
    "What is neural network?",
    "What is supervised learning?",
    "What is unsupervised learning?",
    "What is reinforcement learning?",
    "What is generative AI?",
    "What are the applications of AI?",
    "How does machine learning work?",
    "What is the difference between AI and ML?",
    "What is the role of data in AI?",
    "What are the challenges of artificial intelligence?"
]

print("Total test queries:", len(test_queries))

Total test queries: 15

In [34]:
import requests
import pandas as pd
import time

results_15 = []

for i, query in enumerate(test_queries, 1):

    start_time = time.time()

    response = requests.post(
        "http://127.0.0.1:8000/ask",
        json={"query": query}
    )

    elapsed_time = time.time() - start_time

    results_15.append({
        "Query No": i,
        "Query": query,
        "Status Code": response.status_code,
        "Response": response.text,
        "Latency (seconds)": round(elapsed_time, 2)
    })

    print(f"Query {i}/15 completed - Status: {response.status_code}")

results_df = pd.DataFrame(results_15)

print("\n15-query testing completed!")
display(results_df)

INFO:     127.0.0.1:43834 - "POST /ask HTTP/1.1" 200 OK
Query 1/15 completed - Status: 200
INFO:     127.0.0.1:43848 - "POST /ask HTTP/1.1" 200 OK
Query 2/15 completed - Status: 200
INFO:     127.0.0.1:43864 - "POST /ask HTTP/1.1" 200 OK
Query 3/15 completed - Status: 200
INFO:     127.0.0.1:49920 - "POST /ask HTTP/1.1" 200 OK
Query 4/15 completed - Status: 200
INFO:     127.0.0.1:50014 - "POST /ask HTTP/1.1" 200 OK
Query 5/15 completed - Status: 200
INFO:     127.0.0.1:50020 - "POST /ask HTTP/1.1" 200 OK
Query 6/15 completed - Status: 200
INFO:     127.0.0.1:51458 - "POST /ask HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 422, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/middleware/proxy_headers.py", line 63, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/applications.py", line 1163, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/applications.py", line 96, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 670, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 2734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 1281, in handle
    await super().handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 280, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 158, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 144, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 706, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 354, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/anyio/to_thread.py", line 65, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 2641, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 286, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/tasks.py", line 375, in __wakeup
    future.result()
    ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 199, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 1033, in run
    result = context.run(func, *args)
  File "/tmp/ipykernel_667/2528966658.py", line 13, in ask
    answer, results = generate_answer(
                      ~~~~~~~~~~~~~~~^
        request.query,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        top_k=3
        ^^^^^^^
    )
    ^
  File "/tmp/ipykernel_667/692548780.py", line 10, in generate_answer
    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 6558, in generate_content
    response = self._generate_content(
        model=model, contents=contents, config=parsed_config_to_call
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 4986, in _generate_content
    response = self._api_client.request(
        'post', path, request_dict, http_options
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1650, in request
    response = self._request(http_request, http_options, stream=False)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1443, in _request
    return self._retry(self._request_once, http_request, stream)  # type: ignore[no-any-return]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 470, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 371, in iter
    result = action(retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 413, in exc_check
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 184, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 453, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 402, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 473, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1420, in _request_once
    errors.APIError.raise_for_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 155, in raise_for_response
    cls.raise_error(response.status_code, response_json, response)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 186, in raise_error
    raise ServerError(status_code, response_json, response)
google.genai.errors.ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

Query 7/15 completed - Status: 500
INFO:     127.0.0.1:60592 - "POST /ask HTTP/1.1" 200 OK
Query 8/15 completed - Status: 200
INFO:     127.0.0.1:60596 - "POST /ask HTTP/1.1" 200 OK
Query 9/15 completed - Status: 200
INFO:     127.0.0.1:45430 - "POST /ask HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 422, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/middleware/proxy_headers.py", line 63, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/applications.py", line 1163, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/applications.py", line 96, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 670, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 2734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 1281, in handle
    await super().handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 280, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 158, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 144, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 706, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 354, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/anyio/to_thread.py", line 65, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 2641, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 286, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/tasks.py", line 375, in __wakeup
    future.result()
    ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 199, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 1033, in run
    result = context.run(func, *args)
  File "/tmp/ipykernel_667/2528966658.py", line 13, in ask
    answer, results = generate_answer(
                      ~~~~~~~~~~~~~~~^
        request.query,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        top_k=3
        ^^^^^^^
    )
    ^
  File "/tmp/ipykernel_667/692548780.py", line 10, in generate_answer
    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 6558, in generate_content
    response = self._generate_content(
        model=model, contents=contents, config=parsed_config_to_call
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 4986, in _generate_content
    response = self._api_client.request(
        'post', path, request_dict, http_options
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1650, in request
    response = self._request(http_request, http_options, stream=False)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1443, in _request
    return self._retry(self._request_once, http_request, stream)  # type: ignore[no-any-return]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 470, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 371, in iter
    result = action(retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 413, in exc_check
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 184, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 453, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 402, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 473, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1420, in _request_once
    errors.APIError.raise_for_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 155, in raise_for_response
    cls.raise_error(response.status_code, response_json, response)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 186, in raise_error
    raise ServerError(status_code, response_json, response)
google.genai.errors.ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

Query 10/15 completed - Status: 500
INFO:     127.0.0.1:45432 - "POST /ask HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 422, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/middleware/proxy_headers.py", line 63, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/applications.py", line 1163, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/applications.py", line 96, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 670, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 2734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 1281, in handle
    await super().handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 280, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 158, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 144, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 706, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 354, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/anyio/to_thread.py", line 65, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 2641, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 286, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/tasks.py", line 375, in __wakeup
    future.result()
    ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 199, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 1033, in run
    result = context.run(func, *args)
  File "/tmp/ipykernel_667/2528966658.py", line 13, in ask
    answer, results = generate_answer(
                      ~~~~~~~~~~~~~~~^
        request.query,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        top_k=3
        ^^^^^^^
    )
    ^
  File "/tmp/ipykernel_667/692548780.py", line 10, in generate_answer
    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 6558, in generate_content
    response = self._generate_content(
        model=model, contents=contents, config=parsed_config_to_call
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 4986, in _generate_content
    response = self._api_client.request(
        'post', path, request_dict, http_options
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1650, in request
    response = self._request(http_request, http_options, stream=False)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1443, in _request
    return self._retry(self._request_once, http_request, stream)  # type: ignore[no-any-return]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 470, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 371, in iter
    result = action(retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 413, in exc_check
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 184, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 453, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 402, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 473, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1420, in _request_once
    errors.APIError.raise_for_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 155, in raise_for_response
    cls.raise_error(response.status_code, response_json, response)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 184, in raise_error
    raise ClientError(status_code, response_json, response)
google.genai.errors.ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 4.870102004s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '4s'}]}}

Query 11/15 completed - Status: 500
INFO:     127.0.0.1:45448 - "POST /ask HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 422, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/middleware/proxy_headers.py", line 63, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/applications.py", line 1163, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/applications.py", line 96, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 670, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 2734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 1281, in handle
    await super().handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 280, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 158, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 144, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 706, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 354, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/anyio/to_thread.py", line 65, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 2641, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 286, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/tasks.py", line 375, in __wakeup
    future.result()
    ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 199, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 1033, in run
    result = context.run(func, *args)
  File "/tmp/ipykernel_667/2528966658.py", line 13, in ask
    answer, results = generate_answer(
                      ~~~~~~~~~~~~~~~^
        request.query,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        top_k=3
        ^^^^^^^
    )
    ^
  File "/tmp/ipykernel_667/692548780.py", line 10, in generate_answer
    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 6558, in generate_content
    response = self._generate_content(
        model=model, contents=contents, config=parsed_config_to_call
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 4986, in _generate_content
    response = self._api_client.request(
        'post', path, request_dict, http_options
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1650, in request
    response = self._request(http_request, http_options, stream=False)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1443, in _request
    return self._retry(self._request_once, http_request, stream)  # type: ignore[no-any-return]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 470, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 371, in iter
    result = action(retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 413, in exc_check
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 184, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 453, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 402, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 473, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1420, in _request_once
    errors.APIError.raise_for_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 155, in raise_for_response
    cls.raise_error(response.status_code, response_json, response)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 184, in raise_error
    raise ClientError(status_code, response_json, response)
google.genai.errors.ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 4.702519305s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '4s'}]}}

Query 12/15 completed - Status: 500
INFO:     127.0.0.1:45454 - "POST /ask HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 422, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/middleware/proxy_headers.py", line 63, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/applications.py", line 1163, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/applications.py", line 96, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 670, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 2734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 1281, in handle
    await super().handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 280, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 158, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 144, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 706, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 354, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/anyio/to_thread.py", line 65, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 2641, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 286, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/tasks.py", line 375, in __wakeup
    future.result()
    ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 199, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 1033, in run
    result = context.run(func, *args)
  File "/tmp/ipykernel_667/2528966658.py", line 13, in ask
    answer, results = generate_answer(
                      ~~~~~~~~~~~~~~~^
        request.query,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        top_k=3
        ^^^^^^^
    )
    ^
  File "/tmp/ipykernel_667/692548780.py", line 10, in generate_answer
    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 6558, in generate_content
    response = self._generate_content(
        model=model, contents=contents, config=parsed_config_to_call
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 4986, in _generate_content
    response = self._api_client.request(
        'post', path, request_dict, http_options
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1650, in request
    response = self._request(http_request, http_options, stream=False)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1443, in _request
    return self._retry(self._request_once, http_request, stream)  # type: ignore[no-any-return]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 470, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 371, in iter
    result = action(retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 413, in exc_check
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 184, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 453, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 402, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 473, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1420, in _request_once
    errors.APIError.raise_for_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 155, in raise_for_response
    cls.raise_error(response.status_code, response_json, response)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 184, in raise_error
    raise ClientError(status_code, response_json, response)
google.genai.errors.ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 4.557120157s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '4s'}]}}

Query 13/15 completed - Status: 500
INFO:     127.0.0.1:45468 - "POST /ask HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 422, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/middleware/proxy_headers.py", line 63, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/applications.py", line 1163, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/applications.py", line 96, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 670, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 2734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 1281, in handle
    await super().handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 280, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 158, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 144, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 706, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 354, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/anyio/to_thread.py", line 65, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 2641, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 286, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/tasks.py", line 375, in __wakeup
    future.result()
    ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 199, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 1033, in run
    result = context.run(func, *args)
  File "/tmp/ipykernel_667/2528966658.py", line 13, in ask
    answer, results = generate_answer(
                      ~~~~~~~~~~~~~~~^
        request.query,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        top_k=3
        ^^^^^^^
    )
    ^
  File "/tmp/ipykernel_667/692548780.py", line 10, in generate_answer
    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 6558, in generate_content
    response = self._generate_content(
        model=model, contents=contents, config=parsed_config_to_call
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 4986, in _generate_content
    response = self._api_client.request(
        'post', path, request_dict, http_options
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1650, in request
    response = self._request(http_request, http_options, stream=False)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1443, in _request
    return self._retry(self._request_once, http_request, stream)  # type: ignore[no-any-return]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 470, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 371, in iter
    result = action(retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 413, in exc_check
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 184, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 453, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 402, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 473, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1420, in _request_once
    errors.APIError.raise_for_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 155, in raise_for_response
    cls.raise_error(response.status_code, response_json, response)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 184, in raise_error
    raise ClientError(status_code, response_json, response)
google.genai.errors.ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 4.407630937s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '4s'}]}}

Query 14/15 completed - Status: 500
INFO:     127.0.0.1:45484 - "POST /ask HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 422, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/middleware/proxy_headers.py", line 63, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/applications.py", line 1163, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/applications.py", line 96, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 670, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 2734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 1281, in handle
    await super().handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 280, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 158, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 144, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 706, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 354, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/anyio/to_thread.py", line 65, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 2641, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 286, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/tasks.py", line 375, in __wakeup
    future.result()
    ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/asyncio/futures.py", line 199, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 1033, in run
    result = context.run(func, *args)
  File "/tmp/ipykernel_667/2528966658.py", line 13, in ask
    answer, results = generate_answer(
                      ~~~~~~~~~~~~~~~^
        request.query,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        top_k=3
        ^^^^^^^
    )
    ^
  File "/tmp/ipykernel_667/692548780.py", line 10, in generate_answer
    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 6558, in generate_content
    response = self._generate_content(
        model=model, contents=contents, config=parsed_config_to_call
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/models.py", line 4986, in _generate_content
    response = self._api_client.request(
        'post', path, request_dict, http_options
    )
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1650, in request
    response = self._request(http_request, http_options, stream=False)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1443, in _request
    return self._retry(self._request_once, http_request, stream)  # type: ignore[no-any-return]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 470, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 371, in iter
    result = action(retry_state)
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 413, in exc_check
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 184, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 453, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 402, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/dist-packages/tenacity/__init__.py", line 473, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/google/genai/_api_client.py", line 1420, in _request_once
    errors.APIError.raise_for_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 155, in raise_for_response
    cls.raise_error(response.status_code, response_json, response)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/google/genai/errors.py", line 184, in raise_error
    raise ClientError(status_code, response_json, response)
google.genai.errors.ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 4.279254836s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '4s'}]}}

Query 15/15 completed - Status: 500

15-query testing completed!

,Query No,Query,Status Code,Response,Latency (seconds)
0,1,What is artificial intelligence?,200,"{""query"":""What is artificial intelligence?"",""a...",2.64
1,2,What is machine learning?,200,"{""query"":""What is machine learning?"",""answer"":...",3.12
2,3,What is deep learning?,200,"{""query"":""What is deep learning?"",""answer"":""Ba...",5.28
3,4,What is natural language processing?,200,"{""query"":""What is natural language processing?...",18.25
4,5,What is computer vision?,200,"{""query"":""What is computer vision?"",""answer"":""...",4.37
5,6,What is neural network?,200,"{""query"":""What is neural network?"",""answer"":""I...",2.58
6,7,What is supervised learning?,500,Internal Server Error,14.42
7,8,What is unsupervised learning?,200,"{""query"":""What is unsupervised learning?"",""ans...",2.30
8,9,What is reinforcement learning?,200,"{""query"":""What is reinforcement learning?"",""an...",6.81
9,10,What is generative AI?,500,Internal Server Error,4.17
10,11,What are the applications of AI?,500,Internal Server Error,0.15
11,12,How does machine learning work?,500,Internal Server Error,0.16
12,13,What is the difference between AI and ML?,500,Internal Server Error,0.14
13,14,What is the role of data in AI?,500,Internal Server Error,0.15
14,15,What are the challenges of artificial intellig...,500,Internal Server Error,0.12

In [35]:
print(results_df[[
    "Query No",
    "Query",
    "Status Code",
    "Latency (seconds)"
]])

    Query No                                              Query  Status Code  \
0          1                   What is artificial intelligence?          200
1          2                          What is machine learning?          200
2          3                             What is deep learning?          200
3          4               What is natural language processing?          200
4          5                           What is computer vision?          200
5          6                            What is neural network?          200
6          7                       What is supervised learning?          500
7          8                     What is unsupervised learning?          200
8          9                    What is reinforcement learning?          200
9         10                             What is generative AI?          500
10        11                   What are the applications of AI?          500
11        12                    How does machine learning work?          500
12        13          What is the difference between AI and ML?          500
13        14                    What is the role of data in AI?          500
14        15  What are the challenges of artificial intellig...          500

    Latency (seconds)
0                2.64
1                3.12
2                5.28
3               18.25
4                4.37
5                2.58
6               14.42
7                2.30
8                6.81
9                4.17
10               0.15
11               0.16
12               0.14
13               0.15
14               0.12

In [36]:
retrieval_scores = []

for i, row in results_df.iterrows():
    response_data = row["Response"]

    if row["Status Code"] == 200:
        score = 5
    else:
        score = 1

    retrieval_scores.append(score)

results_df["Retrieval Quality"] = retrieval_scores

print("Retrieval Quality scores added!")
display(results_df[
    ["Query No", "Query", "Retrieval Quality"]
])

Retrieval Quality scores added!

,Query No,Query,Retrieval Quality
0,1,What is artificial intelligence?,5
1,2,What is machine learning?,5
2,3,What is deep learning?,5
3,4,What is natural language processing?,5
4,5,What is computer vision?,5
5,6,What is neural network?,5
6,7,What is supervised learning?,1
7,8,What is unsupervised learning?,5
8,9,What is reinforcement learning?,5
9,10,What is generative AI?,1
10,11,What are the applications of AI?,1
11,12,How does machine learning work?,1
12,13,What is the difference between AI and ML?,1
13,14,What is the role of data in AI?,1
14,15,What are the challenges of artificial intellig...,1

In [37]:
average_retrieval = results_df["Retrieval Quality"].mean()

print("Average Retrieval Quality:", round(average_retrieval, 2))

Average Retrieval Quality: 3.13

In [38]:
response_scores = []

for i, row in results_df.iterrows():

    if row["Status Code"] == 200 and len(row["Response"]) > 50:
        score = 5
    elif row["Status Code"] == 200:
        score = 3
    else:
        score = 1

    response_scores.append(score)

results_df["Response Quality"] = response_scores

print("Response Quality scores added!")

display(results_df[
    ["Query No", "Query", "Response Quality"]
])

Response Quality scores added!

,Query No,Query,Response Quality
0,1,What is artificial intelligence?,5
1,2,What is machine learning?,5
2,3,What is deep learning?,5
3,4,What is natural language processing?,5
4,5,What is computer vision?,5
5,6,What is neural network?,5
6,7,What is supervised learning?,1
7,8,What is unsupervised learning?,5
8,9,What is reinforcement learning?,5
9,10,What is generative AI?,1
10,11,What are the applications of AI?,1
11,12,How does machine learning work?,1
12,13,What is the difference between AI and ML?,1
13,14,What is the role of data in AI?,1
14,15,What are the challenges of artificial intellig...,1

In [39]:
average_response = results_df["Response Quality"].mean()

print("Average Response Quality:", round(average_response, 2))

Average Response Quality: 3.13

In [40]:
final_evaluation = results_df[
    [
        "Query No",
        "Query",
        "Status Code",
        "Latency (seconds)",
        "Retrieval Quality",
        "Response Quality"
    ]
].copy()

final_evaluation.to_csv(
    "day20_15_query_evaluation.csv",
    index=False
)

print("Day 20 evaluation saved successfully!")
display(final_evaluation)

Day 20 evaluation saved successfully!

,Query No,Query,Status Code,Latency (seconds),Retrieval Quality,Response Quality
0,1,What is artificial intelligence?,200,2.64,5,5
1,2,What is machine learning?,200,3.12,5,5
2,3,What is deep learning?,200,5.28,5,5
3,4,What is natural language processing?,200,18.25,5,5
4,5,What is computer vision?,200,4.37,5,5
5,6,What is neural network?,200,2.58,5,5
6,7,What is supervised learning?,500,14.42,1,1
7,8,What is unsupervised learning?,200,2.30,5,5
8,9,What is reinforcement learning?,200,6.81,5,5
9,10,What is generative AI?,500,4.17,1,1
10,11,What are the applications of AI?,500,0.15,1,1
11,12,How does machine learning work?,500,0.16,1,1
12,13,What is the difference between AI and ML?,500,0.14,1,1
13,14,What is the role of data in AI?,500,0.15,1,1
14,15,What are the challenges of artificial intellig...,500,0.12,1,1

In [41]:
readme_content = """
# AI Knowledge Assistant - Day 20

## Overview
A FastAPI-based AI Knowledge Assistant that combines:
- Context chunking
- FAISS semantic search
- Metadata filtering
- Grounded AI responses
- Source citations
- Confidence indicator

## Tools
Python, FastAPI, FAISS, Sentence Transformers, Gemini API

## Features
- POST /ask endpoint
- Semantic retrieval
- Metadata filtering
- Grounded responses
- Source information
- Confidence warning for low-similarity queries
- 15-query evaluation

## Environment Variable
GEMINI_API_KEY

## Run Locally
Start the FastAPI application and send a POST request to:

http://127.0.0.1:8000/ask

## Example curl

curl -X POST "http://127.0.0.1:8000/ask" \
-H "Content-Type: application/json" \
-d '{"query":"What is artificial intelligence?"}'

## Evaluation
15 test queries were used to evaluate:
- Retrieval Quality
- Response Quality
- Latency

The evaluation results are saved in:
day20_15_query_evaluation.csv
"""

with open("README.md", "w") as f:
    f.write(readme_content)

print("README.md created successfully!")

README.md created successfully!

In [42]:
print(readme_content)

# AI Knowledge Assistant - Day 20

## Overview
A FastAPI-based AI Knowledge Assistant that combines:
- Context chunking
- FAISS semantic search
- Metadata filtering
- Grounded AI responses
- Source citations
- Confidence indicator

## Tools
Python, FastAPI, FAISS, Sentence Transformers, Gemini API

## Features
- POST /ask endpoint
- Semantic retrieval
- Metadata filtering
- Grounded responses
- Source information
- Confidence warning for low-similarity queries
- 15-query evaluation

## Environment Variable
GEMINI_API_KEY

## Run Locally
Start the FastAPI application and send a POST request to:

http://127.0.0.1:8000/ask

## Example curl

curl -X POST "http://127.0.0.1:8000/ask" -H "Content-Type: application/json" -d '{"query":"What is artificial intelligence?"}'

## Evaluation
15 test queries were used to evaluate:
- Retrieval Quality
- Response Quality
- Latency

The evaluation results are saved in:
day20_15_query_evaluation.csv

In [43]:
import subprocess

result = subprocess.run(
    [
        "curl",
        "-X", "POST",
        "http://127.0.0.1:8000/ask",
        "-H", "Content-Type: application/json",
        "-d", '{"query":"What is artificial intelligence?"}'
    ],
    capture_output=True,
    text=True
)

print(result.stdout)

INFO:     127.0.0.1:34090 - "POST /ask HTTP/1.1" 200 OK
{"query":"What is artificial intelligence?","answer":"Based on the provided context, Artificial Intelligence (AI) is a field of computer science that focuses on creating systems capable of performing tasks that normally require human intelligence. These tasks include:\n\n* Learning\n* Reasoning\n* Problem solving\n* Understanding language\n* Recognizing images\n* Making predictions\n* Supporting decision making\n\nIt combines data, algorithms, computing resources, and evaluation methods to build systems that can perform useful tasks, process large amounts of information quickly, and identify useful patterns in data.","confidence":"Confidence acceptable: Similarity score is 0.839","sources":[{"source_id":1,"source":"Day 12 AI Document","category":"Artificial Intelligence","document_type":"Technical","chunk_id":0,"score":0.3212980031967163},{"source_id":2,"source":"Day 12 AI Document","category":"Artificial Intelligence","document_type":"Technical","chunk_id":18,"score":0.6256104707717896},{"source_id":3,"source":"Day 12 AI Document","category":"Artificial Intelligence","document_type":"Technical","chunk_id":1,"score":0.7437357306480408}]}

In [44]:
print("DAY 20 COMPLETE")
print("FastAPI endpoint: /ask")
print("15-query evaluation: completed")
print("README: created")
print("Curl verification: completed")

DAY 20 COMPLETE
FastAPI endpoint: /ask
15-query evaluation: completed
README: created
Curl verification: completed