In [ ]:
!pip install -q fastapi uvicorn langchain langchain-openai faiss-cpu python-dotenv

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.4/127.4 kB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 49.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.1/572.1 kB 28.5 MB/s eta 0:00:00

In [2]:
!pip install -q langchain langchain-community langchain-openai \
langchain-text-splitters langchain-huggingface \
sentence-transformers faiss-cpu fastapi uvicorn python-dotenv

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 42.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 4.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [3]:
!pip install -q requests==2.32.4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 781.1 kB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-community 0.4.2 requires requests<3.0.0,>=2.32.5, but you have requests 2.32.4 which is incompatible.

In [4]:
import requests
import fastapi
import uvicorn
import langchain
import faiss

print("FastAPI:", fastapi.__version__)
print("LangChain:", langchain.__version__)
print("Requests:", requests.__version__)
print("All imports successful!")

FastAPI: 0.141.1
LangChain: 1.3.18
Requests: 2.32.4
All imports successful!

In [5]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

print("Chunking pipeline ready!")
print("Chunk size:", 500)
print("Chunk overlap:", 50)

Chunking pipeline ready!
Chunk size: 500
Chunk overlap: 50

In [6]:
from langchain_core.documents import Document

# Day 12 ka document
document = """
Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making.

Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later make predictions or decisions based
on new information.

Supervised learning uses labeled data. Classification predicts categories,
while regression predicts numerical values.

Unsupervised learning works with data where predefined output labels are not
available. Clustering is a common unsupervised learning technique.

Reinforcement learning allows an agent to learn through feedback and rewards.

Deep learning is a branch of machine learning based on artificial neural
networks and is useful for image recognition, speech recognition and NLP.

Natural Language Processing enables computers to work with human language.
"""

# Day 12 chunking
recursive_chunks = text_splitter.split_text(document)

# Day 17 style metadata documents
documents = []

for i, chunk in enumerate(recursive_chunks):
    documents.append(
        Document(
            page_content=chunk,
            metadata={
                "source": "AI Research Report",
                "category": "Artificial Intelligence",
                "date": "2026-09-25",
                "document_type": "Technical",
                "chunk_id": i
            }
        )
    )

print("Total chunks:", len(documents))
print("\nFirst chunk:")
print(documents[0].page_content)

print("\nMetadata:")
print(documents[0].metadata)

Total chunks: 3

First chunk:
Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making.

Metadata:
{'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}

In [7]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# Day 14: Embedding model
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# Create FAISS vector store from our metadata documents
vectorstore = FAISS.from_documents(
    documents,
    embeddings
)

print("FAISS vector store created successfully!")
print("Total indexed documents:", len(documents))

/tmp/ipykernel_7148/3023166215.py:2: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

FAISS vector store created successfully!
Total indexed documents: 3

In [8]:
query = "What is machine learning?"

results = vectorstore.similarity_search(
    query,
    k=3,
    filter={
        "category": "Artificial Intelligence"
    }
)

print("Query:", query)
print("\nFiltered Results:\n")

for i, doc in enumerate(results, start=1):
    print(f"--- Result {i} ---")
    print("Source:", doc.metadata["source"])
    print("Category:", doc.metadata["category"])
    print("Chunk ID:", doc.metadata["chunk_id"])
    print("Content:", doc.page_content[:200])
    print()

Query: What is machine learning?

Filtered Results:

--- Result 1 ---
Source: AI Research Report
Category: Artificial Intelligence
Chunk ID: 1
Content: Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later ma

--- Result 2 ---
Source: AI Research Report
Category: Artificial Intelligence
Chunk ID: 2
Content: Unsupervised learning works with data where predefined output labels are not
available. Clustering is a common unsupervised learning technique.

Reinforcement learning allows an agent to learn through

--- Result 3 ---
Source: AI Research Report
Category: Artificial Intelligence
Chunk ID: 0
Content: Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, p

In [9]:
GROUNDING_PROMPT = """
You are a grounded AI assistant.

Answer the user's question ONLY using the provided context.

Rules:
1. Do not use outside knowledge.
2. If the answer is not present in the context, say:
   "I don't have enough information in the provided context."
3. Keep the answer concise and factual.
4. Mention the source when possible.

Context:
{context}

Question:
{question}

Answer:
"""

print("Grounded RAG prompt created successfully!")

Grounded RAG prompt created successfully!

In [10]:
def retrieve_context(query, k=3):
    results = vectorstore.similarity_search(
        query,
        k=k,
        filter={
            "category": "Artificial Intelligence"
        }
    )

    context_parts = []

    for doc in results:
        context_parts.append(
            f"Source: {doc.metadata['source']}\n"
            f"Chunk ID: {doc.metadata['chunk_id']}\n"
            f"Content: {doc.page_content}"
        )

    return results, "\n\n".join(context_parts)


# Test retrieval
query = "What is machine learning?"

results, context = retrieve_context(query)

print("Retrieved chunks:", len(results))
print("\n" + context[:1500])

Retrieved chunks: 3

Source: AI Research Report
Chunk ID: 1
Content: Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later make predictions or decisions based
on new information.

Supervised learning uses labeled data. Classification predicts categories,
while regression predicts numerical values.

Source: AI Research Report
Chunk ID: 2
Content: Unsupervised learning works with data where predefined output labels are not
available. Clustering is a common unsupervised learning technique.

Reinforcement learning allows an agent to learn through feedback and rewards.

Deep learning is a branch of machine learning based on artificial neural
networks and is useful for image recognition, speech recognition and NLP.

Natural Language Processing enables computers to work with human language.

Source: AI Research Report
Chunk ID: 0
Content: Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making.

In [11]:
def build_rag_prompt(query):
    results, context = retrieve_context(query)

    prompt = GROUNDING_PROMPT.format(
        context=context,
        question=query
    )

    return results, prompt


# Test
query = "What is machine learning?"

results, rag_prompt = build_rag_prompt(query)

print(rag_prompt)

You are a grounded AI assistant.

Answer the user's question ONLY using the provided context.

Rules:
1. Do not use outside knowledge.
2. If the answer is not present in the context, say:
   "I don't have enough information in the provided context."
3. Keep the answer concise and factual.
4. Mention the source when possible.

Context:
Source: AI Research Report
Chunk ID: 1
Content: Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later make predictions or decisions based
on new information.

Supervised learning uses labeled data. Classification predicts categories,
while regression predicts numerical values.

Source: AI Research Report
Chunk ID: 2
Content: Unsupervised learning works with data where predefined output labels are not
available. Clustering is a common unsupervised learning technique.

Reinforcement learning allows an agent to learn through feedback and rewards.

Deep learning is a branch of machine learning based on artificial neural
networks and is useful for image recognition, speech recognition and NLP.

Natural Language Processing enables computers to work with human language.

Source: AI Research Report
Chunk ID: 0
Content: Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making.

Question:
What is machine learning?

Answer:

In [13]:
!pip install -q langchain-google-genai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 705.6 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.6/81.6 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 262.5/262.5 kB 9.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.58.1 which is incompatible.

In [30]:
from google.colab import userdata
from langchain_google_genai import ChatGoogleGenerativeAI

gemini_api_key = userdata.get("Day20_Gemini")

llm = ChatGoogleGenerativeAI(
    model="gemini-3.8-flash",
    google_api_key=gemini_api_key
)

print("Gemini LLM connected successfully!")

Gemini LLM connected successfully!

In [19]:
from google.colab import userdata
from langchain_google_genai import ChatGoogleGenerativeAI

gemini_api_key = userdata.get("Day20_Gemini")

llm = ChatGoogleGenerativeAI(
    model="gemini-3.8-flash",
    google_api_key=gemini_api_key
)

print("Gemini LLM connected successfully!")

Gemini LLM connected successfully!

In [20]:
def generate_answer(query):
    results, rag_prompt = build_rag_prompt(query)

    response = llm.invoke(rag_prompt)

    return response.content, results


query = "What is machine learning?"

answer, sources = generate_answer(query)

print("Answer:")
print(answer)

print("\nSources:")
for doc in sources:
    print(
        f"- {doc.metadata['source']} | "
        f"Chunk {doc.metadata['chunk_id']}"
    )

Answer:
[{'type': 'text', 'text': 'Based on the AI Research Report (Chunk ID: 1), machine learning allows a computer system to learn patterns from data rather than being explicitly programmed for every individual task. It involves training a model using data so that it can later make predictions or decisions based on new information.', 'extras': {'signature': 'EuQNCuENAWkUfRMoDtLiknPTSwXLJYdI7BqkH8lHnJxbJj9wCjKIo0/MzTxuwDuxcJs7EXItXxadTUR/UkQhI44BU8QjoQHHMNlC0p2csmT4Fne9Em3cZEwfVmik+kdtt/doSqgKpSGFcWGgSLXr6SDqCxN4q4rWJf76vT5GMEL3XWE2TWCd9DOm+fkC9FoKCcCtyYsU3d1uz9p+qdbbkFYpEfdnk7BMcS4C9LfFnyDYacylzlhoj+oB9d2Ji6WhClrdh3YS6JQFoK743AFwGd0tfLwSqJGMhjif7w7hXiEWsENy8yOL4IKuLgXYirWY/WHbdHZqrCic7nvQDbhnAyi7R1gLHqgnk1vcBA1nyPkP//Rpck/WeCgzLDsxF2T7oiA2lw3KaRjgTi3OQhVU0Lj8HTN0rhBWResLX/G2ChiUEi4Q0yORj2zKYo8XMKthrZz5qYHz1QgtH+vm7CWMhWzmm4XrOnxxy/hhNvnjunhC775iJNncfLRDc/wJADz9Bso0GmdgB7x96WyFiyZx0ks130D3G5FUOr17Wfe0N/kY3p9YGadaYQCMKFHQNY3c6JdGlUtv6c2MImcES4J/OKzZddl5h739yTLIiC5Q3z1P/YYADeTILtmSU6dwKqimYjOMmbaZV0e+KXhi0QvTY9Vk0QZMdaarf71SyQLPbIms1Nc8/O134s+i4U2F/RGg60SldbAqYNYSHqTXKPYpyIWcBkA3v+ipGWmUA0dXxZwOu5uyRa0n31rLQMoSMSSsHJs4yjDFgUpDuvN4JjLGggJlaDk5vTsOHtnrpLWAazfGOoLpYFC5Mntg4byrPem3JNqWW2EZF2lz5fuFhGAEPnMddZRMUCWb0/89VvCBLpMYE4Fa/8H8TRBvnJAw6Oy7RVQDZSDM29l6bvF9C65hhvYKmx8QQ4Ow/GxDUUqCjOn/ZocDpoNAjW/iqYCjHEVLq4X5JHOPCVXGCibuj/XK8bzFBDC1JXErYpjm7KlEbDWF8p5QzD7HZZwf6RfK72eDnaJHeVquWJIWK1Qx0ASUd5hcGiZvMW5FoaILkogYHzDczlKESKb0S/DWFJCeNZvPP1O30q9eZLLC+TApT+Psa8RD83w9pEvQ/+ug/vmiJzhGfMWSWTVcztD5lQrmf+xaXLLQV5O9Km8LF/tWfZImcewvSgEgbJ/yBI1p66CiPSJ07J/b8Vk6EOich73Uh3o0zpqMwd7wp+eYJeE6kyl6OyvN9Ed5Qg+PaAc+CAsZAwxJYBtz3IyZLRgemboUoqizJwhkT7YrzI7kgsk+hUFiua95gL+9oiIV9s0ycPkHZLFqntisUWY31iHZbtqF0oy4RSxOGCnM4wV93wBOus/hAa6kDT23dS7ZFxsAgnaoEGHYezpDx9X2/CYyC/ptiwqgpVZaXbRJlzw6eESTZie/XyWjZudjLHGW6A3rI19M8tRXACwAbisFlRFwnlEjX7VLwCbzR9kY1/oAlZvpJU8T2k8XyD+7Qu/cz2I3/KCUPp7mPw5SyMif3ni734qEn+e1V6lhWAgANc75sq7YOua+l3lG5JucjWWrrQ/yQNfz1YVJyvl6Kq/+WNQ7in/3CM8kTbTWTU2DrnB976klwX8UiQKB8CQScLJaaf48I8q7JdX9I6S7HshZzt9BeCZrFOsd6gDFed6RQvhteG8QtHTzEqtbInLMdAv9E0xmZVsOo8PCLYUOSG/7/1xV0Hbpo6m9b8kgfIn7FDyitSrsI0W3Mf7L2EekXLJoV4myeLcmZur+QUqrmmmKXxnDmaRBu0bJ1H5CFRA00pZdV8584zj8PwVEyxi9jAjedTUVnjS/y/K9Q2xH20Om5g1eCAWQ3+CWaqE70R2+I6XBThC6htQ3KBlU2e284zpBCCnwAet8RTQwbiHMcxMc3b72nzOkQVZb0TVjjF9MidbJNrUJUMzHHFcrD/3PDX2mD0+i9gu8vbheAcEgP93hIhuwGZRGil5g7/iZpSNSJe+252CPigM9fQqTNDklhcfVkepTt/Flu16KgkaBCDOrofTQTUg3h8NeMdTPZ2gs+x0xfZfxHLy1xzaE26Ij9XO3oq6++WwSTzEmd4lok51lhyjX0qSgfSX/gOWjRAOL1eOSJOrgBOvasK+E7mxEzeyCnXhB4BOMB2yxlLOsqHlnMYU7umWdiHTMwEraOeog7slC8VaDkq5gaYvByC67buKDvlaFpU9lWA3alm1Ip8aXZ9TZPeelKo2Xz+oU/mr+LQYLIAdxWl6wYQJCT+3tT3qmwBNErIHvrtde6r03+TdFe6jkedYalEMt9TzDt3KXOxUs7qAP0+L7hgpgIIXFZdkzJnKlmoAP5gcfGilAQJWj'}}]

Sources:
- AI Research Report | Chunk 1
- AI Research Report | Chunk 2
- AI Research Report | Chunk 0

In [21]:
def retrieve_with_score(query, k=3):
    results = vectorstore.similarity_search_with_relevance_scores(
        query,
        k=k,
        filter={
            "category": "Artificial Intelligence"
        }
    )

    return results


query = "What is machine learning?"

results_with_scores = retrieve_with_score(query)

print("Query:", query)
print("\nRetrieved Results:\n")

for i, (doc, score) in enumerate(results_with_scores, start=1):
    print(f"--- Result {i} ---")
    print("Similarity Score:", round(score, 3))
    print("Source:", doc.metadata["source"])
    print("Chunk ID:", doc.metadata["chunk_id"])
    print("Content:", doc.page_content[:200])
    print()

Query: What is machine learning?

Retrieved Results:

--- Result 1 ---
Similarity Score: 0.658
Source: AI Research Report
Chunk ID: 1
Content: Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later ma

--- Result 2 ---
Similarity Score: 0.347
Source: AI Research Report
Chunk ID: 2
Content: Unsupervised learning works with data where predefined output labels are not
available. Clustering is a common unsupervised learning technique.

Reinforcement learning allows an agent to learn through

--- Result 3 ---
Similarity Score: 0.327
Source: AI Research Report
Chunk ID: 0
Content: Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, p

In [23]:
def generate_answer_with_confidence(query, threshold=0.3):
    results_with_scores = retrieve_with_score(query)

    if not results_with_scores:
        return "I don't have enough information in the provided context.", []

    best_doc, best_score = results_with_scores[0]

    if best_score < threshold:
        return (
            "Warning: Low confidence. "
            "I don't have enough information in the provided context."
        ), results_with_scores

    results, rag_prompt = build_rag_prompt(query)
    response = llm.invoke(rag_prompt)

    return response.content, results_with_scores


query = "What is machine learning?"

answer, scored_sources = generate_answer_with_confidence(query)

print("Answer:")
print(answer)

print("\nSources:")
for doc, score in scored_sources:
    print(
        f"- {doc.metadata['source']} | "
        f"Chunk {doc.metadata['chunk_id']} | "
        f"Score: {score:.3f}"
    )

Answer:
[{'type': 'text', 'text': 'Based on the AI Research Report (Chunk ID: 1), machine learning allows a computer system to learn patterns from data rather than being explicitly programmed for every individual task. A machine learning model is trained using data and can later make predictions or decisions based on new information.', 'extras': {'signature': 'EqoNCqcNAWkUfRMSkm6WYHXTX5XBBUuzWLjlxm3M9ExkfAKyhdMf0o3jLKCLOxvPZbn8zqGyE9lhivYuli6PdIe6n3dcmi7h0YpRGGZUzUAqDnGoUU0V/UtCqINnoNJoO3O2awc2YTO3lrUvikRrdInvtgJutyWMPSpowuW2kV1psZL0vq0/oiqTbVK9Fscvj64ru51MJF34H/l1SM7tLZFluFcZ65KB2dRRBd0NV9SPAEugOgpgVZfVXeAuHcDTXrgHePwOqxsM+DEPC/qqBoiiWZUJwBEPgBrpaUkGeFcVqGSDvVuOH9UICHmLDwgESa+ape2wKARDmTQv/fbkbuLRd4A1NJqXDbLEhtSHfOWwwH9Trff+b4Mn46NGi+DZvt89UIZ5eddgaJME7DTUH1fQqyQXFSVyogXwxbyEsw6m5wSDRgMWihAR1PFIpCu12YTu5u4HdfhJ8hVfyajacw0LNr61jSuYH8+PbRs9axokK/Po2KmOVRSWeJsmTmmVsN4V1BNhTczTnMBR5B2iJvsBPRhduc2boueY4aG9Me5v96FLzLhj2Fn9nPGiNc+k6JDV8ByHLnxk47ode4sGZHLQU5wh0g9HHsKPpI/Ik606//eNRtTrjqgWSdcNQpRnig7kveth7JOlkEWBxaJyvyLfsGYWTxRp/czpxlacpsYaCV+xf7WEIs5xkD3HbmttHUIpcNl9oEaTRqQtpkYIeHyWFRLRvYRxO0CDlQErI8bX2KbATQCngI1mqa7bKqH38Txu1hnEDhVgJxoItdDTo5Q9dv8iN7MJHlpwrnGHrZEXD5DOPGbaASMzIRSOfLl/UMp8XvDq4Nze1757glWfrHsl+qBblilbyznm5wdjNwcre2hf0zBCYYIb2/4OvvZo5frLy2DHF4NFy20H7e92HGH4c0MwWmdk1dMmiA6aeHy8utjT8VU/8i1biYtySUv8AQ1sNKKL+KkLXKiWSSgTgzZh/6YyDMpZGIemIY9WLUnUgmaxGAnCnaR2lcXoLfvpX2gwq2iobXo49XRaKO9JM01j/YWFQX+e/8IZ+Vm4oS+VXq23smzm3N1lFMOrm/Vf63N/hbF1l3ph+p0p5jmLh3c2IoJWu8ZKL8daEReDD0FjxWlcDJH+3bcEvKRCPd9Xu6vasKPyxCLaSTyYXJWiAWU1pU2vRYGAImIMTNP2kExKFI/nZAMacjeLiGmC4Hrl0eNts0C1ImwwLMNe6MYUQ0WA+MOC8Ae7IsbpYEo5immaMc/mjnHqcpaIQ/f1ktDmgQCCcYrfW16gsogfds3WoF+zXlylJpfBPI5CNe6NMmltuVHms7xyqQ05xzG2uGQGhWqUHd/3kWq59tKGUxeDGU4YZQlup14vUSiQQs7QmCVEEL5Wpd2H42PLx/pTruWzIHvzvpZ7tWmO5Q/Y2Hf4WuQIZ9YLtq+yY/PzvKOh5pncLG1xmwtIv3X7Gd+hifCiy2GjH1THHNpOblA+4C4fvJPfFU43vngUi5QyOLd58jt51/Zj1oBXeWDoAxv51c2PYk4/8OA9RzUqpyDlymlWFZI9OPVrqrMpi7tcgkWdpAJDDCB7rHVjCmgJCNaF5Yev4b0qQ0VmStK517zYIbcZWg1bRukjOIDGJCGvcc1CVwZkIHE+l/a3WZSpJSipR5hkF01pzuAOjvtPj6xo0k9dBt+a3Fed64xB5mlqdVPDuOt5CZufAEcXoXYX50MvBHhPP6LxoF/oaRY4EErF9MOnPG1cdiDwjyfgYajkRopSuk9WYUYkysc5M46iUEbDqWa6uivXYd7IYsn1eyWjDx3Dd40CKoKqr9TlsUPOf/AFP7iB7XYKdtEp5bmPVRQ+5pSktQdXvyNJKK+686YI/1HKXFv+maShwiXMG7cvMC0uttW+DFN9ZpRe055LXzDyznSOlc2wqTZdpSqY/o+oePKPGhw/2bvwx7DO9LgY+GlLA3H0m+p0IS6N5vw6HxXXsLpJWENHa8p/Yq2nNWiTnA+0DVSa3WYSb4cHw+5DQzEo52S1uPEdGHs1ZJxFjaMopkAiqUIfftK+OKrbiigxmxaCV0agN078OopBUmiCYlpPYJE1gLUzPo84/5wkZUCjxMFVr235x4B+wvHplwLj739vs8uGEyW5S9Cf8WATsyc8h18LpmON1kLcih2GG/hQPl8FhRGlGUcEOQLK8WtpdKd0aW4eVBVJRx7L4dcUcXc7OG1T/PkJcGarsoygiw4//IXIefXBgasiBHcgH6Mp4WivR9aj3rUiHLB2PFK4pYU='}}]

Sources:
- AI Research Report | Chunk 1 | Score: 0.658
- AI Research Report | Chunk 2 | Score: 0.347
- AI Research Report | Chunk 0 | Score: 0.327

In [24]:
test_query = "What is the capital of France?"

answer, scored_sources = generate_answer_with_confidence(test_query)

print("Test Query:")
print(test_query)

print("\nAnswer:")
print(answer)

print("\nScores:")
for doc, score in scored_sources:
    print(f"Chunk {doc.metadata['chunk_id']} | Score: {score:.3f}")

Test Query:
What is the capital of France?

Answer:
Warning: Low confidence. I don't have enough information in the provided context.

Scores:
Chunk 0 | Score: -0.329
Chunk 1 | Score: -0.356
Chunk 2 | Score: -0.390

/tmp/ipykernel_7148/391011206.py:2: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='db343db5-5ae2-48b2-89b2-ff69deb559d3', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.3285669)), (Document(id='8788cc1d-edf3-4826-ae84-4728b351ac35', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(-0.35617566)), (Document(id='b04f3d8c-6d52-4cfb-a9a7-0508bede0c58', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(-0.39047432))]
  results = vectorstore.similarity_search_with_relevance_scores(

In [25]:
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Day 20 RAG Knowledge Assistant")


class AskRequest(BaseModel):
    question: str


@app.post("/ask")
def ask_question(request: AskRequest):

    answer, scored_sources = generate_answer_with_confidence(
        request.question
    )

    sources = []

    for doc, score in scored_sources:
        sources.append({
            "source": doc.metadata["source"],
            "chunk_id": doc.metadata["chunk_id"],
            "score": round(score, 3)
        })

    return {
        "question": request.question,
        "answer": answer,
        "sources": sources
    }


print("FastAPI RAG API created successfully!")
print("Endpoint: POST /ask")

FastAPI RAG API created successfully!
Endpoint: POST /ask

In [31]:
test_request = AskRequest(
    question="What is supervised learning?"
)

result = ask_question(test_request)

print("Question:")
print(result["question"])

print("\nAnswer:")
print(result["answer"])

print("\nSources:")
for source in result["sources"]:
    print(source)

Question:
What is supervised learning?

Answer:
[{'type': 'text', 'text': 'Based on the AI Research Report (Chunk ID: 1), supervised learning is a type of learning that uses labeled data. Within supervised learning, classification predicts categories, while regression predicts numerical values.', 'extras': {'signature': 'EtEICs4IAWkUfRMmSvxfXuAFpRdO6WHP+UUTYMDgT074MFuyxeG4fFpDR/R/y46mDtFAAinctSGJLENyQOYVU4Rk+AupJO1WXdkHU/1fgozha5kE5xA79D6qAugvzK5Z8jM1QP8F2YGHyQRkHqKN2EEl0UKam3GN4sSuWCkoI5CY+YO3qoTM04Gvc6qgWXtcFCA611Cs78trCTk4hPGLeqz6vt47AnZwDI0rd7uCG1KsEYnp3Myw3rS8QcsqW5lh24i+HpmZBxlhThDaK3hTw+niGIZ5G5Pj2QpMVqZ8KYYJaAsmFfipiyT1lvsj8ToHPKxMjfseEj8RonJXXm1imDLsAzH7XDFqvR5E4lHRelX1l+iy/MqMUenKKw9RWBWfQr+JsWM/pUu7vUVsnZOTNJNtEuEg7fpI+gq6iPQkRe1j2LM3KeM9vcClv4j8Xezji02yyqbr/uTcoDKWw0JM5LNsa6kcPwBZXvH07FlpzVexohHgdUU64a7HlKd31Yn37iioYI4zJ6sUpX1DYKBtTYZzMNDnr6JmDBstnl/SrofjR22GwQNJXZFhkzImQBdIwvTsdpI57FtnjDBEEUeTbx8ZJPIFl6tjpCY9EBXhZkJc2MuJ6QYbvleKymBJcbvicF27OEFzL4O3vUqHsxTZzYIpDaFffV1fXZ88ODdxMVkEOFq+HCKQm1u0baamgWu0QLKGWq9dcrPqlNEOVCGXBIfzoc54XvwaqML2cewB+Zkw1mGC9S++yv3sRKyiEoEmwudziwt9sSnqMH8su/bMQIg2sHwGaMNmQaEhWrBX/gwY925Fq4Ud7rc8LwdBsLNiah3zQjHRWJYJLV2c7ixfW/JUibNT9YKAnT5Vg+1vesGfN3WHyGH0Anbp69qo16VFNoX/6F1fcCBsARVBiewyb78Vq3cibz8Y9NwrzsQVElPVfl2Lt+Z5jLKP0QbyWZbwcO1oXnd81Yb0Pd0IpB2ADSh6xx0K8d76R4rE0B/NBASsFb+pIS79pXzW526DnCvb+FvLt9soNoMD29xX4xdNDL17FCQkwn766j7vn93STNm7eLFKjJGl8r1cXho0/KXvSDbyAegSruhcc10iqzFsiJ0feZqdCiYQ/QQPg9dqPxXL0HiW6K8C9evrfgzhIXbvIXMwEGDI26e3ZbnmQHpx2Yp0egbwNh2JvRXQnlThz5lrZjA77tYKGWROkR3X/cBtbAkNaYWuL7/oVZO3sDod8TZcRPNPw02NxEmAvKj1e7yPDqr1h3lH0YkCmQZqzlwWBmOiFS0uzoJSo5zYzE+Fpg6p4VmilmzfVdCo6QEWT6nT+AHeqvH7Tyvm+E2NCH81CstYksFKvBxtjR/la+XLJAfA7vzZxKBJ5Dh6haoDm8aWonQZgdopFrRCB9Allz4dsoyxdWFyKOuy1aVdDsVCn9KDnLBmm7SX/TRgMdKNacs1DMltepyjepj7MMGavtMTIVD1kg=='}}]

Sources:
{'source': 'AI Research Report', 'chunk_id': 1, 'score': np.float32(0.479)}
{'source': 'AI Research Report', 'chunk_id': 2, 'score': np.float32(0.377)}
{'source': 'AI Research Report', 'chunk_id': 0, 'score': np.float32(0.073)}

In [33]:
!pip install -q nest-asyncio

In [35]:
import nest_asyncio
import uvicorn

nest_asyncio.apply()

config = uvicorn.Config(app, host="0.0.0.0", port=8000)
server = uvicorn.Server(config)

await server.serve()

INFO:     Started server process [7148]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [7148]

In [ ]:
import requests

url = "http://127.0.0.1:8000/ask"

payload = {
    "question": "What is machine learning?"
}

response = requests.post(url, json=payload)

print("Status Code:", response.status_code)
print("\nResponse:")
print(response.json())

In [1]:
!pip install -q fastapi uvicorn langchain langchain-openai faiss-cpu python-dotenv

In [2]:
!pip install -q requests==2.32.4

In [3]:
import requests
import fastapi
import uvicorn
import langchain
import faiss

print("FastAPI:", fastapi.__version__)
print("LangChain:", langchain.__version__)
print("Requests:", requests.__version__)
print("All imports successful!")

FastAPI: 0.141.1
LangChain: 1.3.18
Requests: 2.32.4
All imports successful!

In [4]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

print("Chunking pipeline ready!")
print("Chunk size:", 500)
print("Chunk overlap:", 50)

Chunking pipeline ready!
Chunk size: 500
Chunk overlap: 50

In [5]:
from langchain_core.documents import Document

document = """
Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making.

Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later make predictions or decisions based
on new information.

Supervised learning uses labeled data. Classification predicts categories,
while regression predicts numerical values.

Unsupervised learning works with data where predefined output labels are not
available. Clustering is a common unsupervised learning technique.

Reinforcement learning allows an agent to learn through feedback and rewards.

Deep learning is a branch of machine learning based on artificial neural
networks and is useful for image recognition, speech recognition and NLP.

Natural Language Processing enables computers to work with human language.
"""

recursive_chunks = text_splitter.split_text(document)

documents = []

for i, chunk in enumerate(recursive_chunks):
    documents.append(
        Document(
            page_content=chunk,
            metadata={
                "source": "AI Research Report",
                "category": "Artificial Intelligence",
                "date": "2026-09-25",
                "document_type": "Technical",
                "chunk_id": i
            }
        )
    )

print("Total chunks:", len(documents))
print("\nFirst chunk:")
print(documents[0].page_content)

print("\nMetadata:")
print(documents[0].metadata)

Total chunks: 3

First chunk:
Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making.

Metadata:
{'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}

In [6]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = FAISS.from_documents(
    documents,
    embeddings
)

print("FAISS vector store created successfully!")
print("Total indexed documents:", len(documents))

/tmp/ipykernel_27548/316213402.py:2: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

FAISS vector store created successfully!
Total indexed documents: 3

In [7]:
query = "What is machine learning?"

results = vectorstore.similarity_search(
    query,
    k=3,
    filter={
        "category": "Artificial Intelligence"
    }
)

print("Query:", query)
print("\nFiltered Results:\n")

for i, doc in enumerate(results, start=1):
    print(f"--- Result {i} ---")
    print("Source:", doc.metadata["source"])
    print("Category:", doc.metadata["category"])
    print("Chunk ID:", doc.metadata["chunk_id"])
    print("Content:", doc.page_content[:200])
    print()

Query: What is machine learning?

Filtered Results:

--- Result 1 ---
Source: AI Research Report
Category: Artificial Intelligence
Chunk ID: 1
Content: Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later ma

--- Result 2 ---
Source: AI Research Report
Category: Artificial Intelligence
Chunk ID: 2
Content: Unsupervised learning works with data where predefined output labels are not
available. Clustering is a common unsupervised learning technique.

Reinforcement learning allows an agent to learn through

--- Result 3 ---
Source: AI Research Report
Category: Artificial Intelligence
Chunk ID: 0
Content: Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, p

In [8]:
GROUNDING_PROMPT = """
You are a grounded AI assistant.

Answer the user's question ONLY using the provided context.

Rules:
1. Do not use outside knowledge.
2. If the answer is not present in the context, say:
   "I don't have enough information in the provided context."
3. Keep the answer concise and factual.
4. Mention the source when possible.

Context:
{context}

Question:
{question}

Answer:
"""

print("Grounded RAG prompt created successfully!")

Grounded RAG prompt created successfully!

In [9]:
def retrieve_context(query, k=3):
    results = vectorstore.similarity_search(
        query,
        k=k,
        filter={
            "category": "Artificial Intelligence"
        }
    )

    context_parts = []

    for doc in results:
        context_parts.append(
            f"Source: {doc.metadata['source']}\n"
            f"Chunk ID: {doc.metadata['chunk_id']}\n"
            f"Content: {doc.page_content}"
        )

    return results, "\n\n".join(context_parts)


query = "What is machine learning?"

results, context = retrieve_context(query)

print("Retrieved chunks:", len(results))
print("\n" + context[:1500])

Retrieved chunks: 3

Source: AI Research Report
Chunk ID: 1
Content: Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later make predictions or decisions based
on new information.

Supervised learning uses labeled data. Classification predicts categories,
while regression predicts numerical values.

Source: AI Research Report
Chunk ID: 2
Content: Unsupervised learning works with data where predefined output labels are not
available. Clustering is a common unsupervised learning technique.

Reinforcement learning allows an agent to learn through feedback and rewards.

Deep learning is a branch of machine learning based on artificial neural
networks and is useful for image recognition, speech recognition and NLP.

Natural Language Processing enables computers to work with human language.

Source: AI Research Report
Chunk ID: 0
Content: Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making.

In [10]:
def build_rag_prompt(query):
    results, context = retrieve_context(query)

    prompt = GROUNDING_PROMPT.format(
        context=context,
        question=query
    )

    return results, prompt


query = "What is machine learning?"

results, rag_prompt = build_rag_prompt(query)

print(rag_prompt)

You are a grounded AI assistant.

Answer the user's question ONLY using the provided context.

Rules:
1. Do not use outside knowledge.
2. If the answer is not present in the context, say:
   "I don't have enough information in the provided context."
3. Keep the answer concise and factual.
4. Mention the source when possible.

Context:
Source: AI Research Report
Chunk ID: 1
Content: Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later make predictions or decisions based
on new information.

Supervised learning uses labeled data. Classification predicts categories,
while regression predicts numerical values.

Source: AI Research Report
Chunk ID: 2
Content: Unsupervised learning works with data where predefined output labels are not
available. Clustering is a common unsupervised learning technique.

Reinforcement learning allows an agent to learn through feedback and rewards.

Deep learning is a branch of machine learning based on artificial neural
networks and is useful for image recognition, speech recognition and NLP.

Natural Language Processing enables computers to work with human language.

Source: AI Research Report
Chunk ID: 0
Content: Artificial Intelligence is a field of computer science that focuses on creating
systems capable of performing tasks that normally require human intelligence.
These tasks include learning, reasoning, problem solving, understanding language,
recognizing images, making predictions, and supporting decision making.

Question:
What is machine learning?

Answer:

In [11]:
from google.colab import userdata
from langchain_google_genai import ChatGoogleGenerativeAI

gemini_api_key = userdata.get("Day20_Gemini")

llm = ChatGoogleGenerativeAI(
    model="gemini-3.8-flash",
    google_api_key=gemini_api_key
)

print("Gemini LLM connected successfully!")

Gemini LLM connected successfully!

In [12]:
def retrieve_with_score(query, k=3):
    results = vectorstore.similarity_search_with_relevance_scores(
        query,
        k=k,
        filter={
            "category": "Artificial Intelligence"
        }
    )
    return results


def generate_answer_with_confidence(query, threshold=0.3):
    results_with_scores = retrieve_with_score(query)

    if not results_with_scores:
        return "I don't have enough information in the provided context.", []

    best_doc, best_score = results_with_scores[0]

    if best_score < threshold:
        return (
            "Warning: Low confidence. "
            "I don't have enough information in the provided context."
        ), results_with_scores

    results, rag_prompt = build_rag_prompt(query)

    response = llm.invoke(rag_prompt)

    return response.content, results_with_scores


print("Confidence-based RAG function ready!")

Confidence-based RAG function ready!

In [13]:
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Day 20 RAG Knowledge Assistant")


class AskRequest(BaseModel):
    question: str


@app.post("/ask")
def ask_question(request: AskRequest):

    answer, scored_sources = generate_answer_with_confidence(
        request.question
    )

    sources = []

    for doc, score in scored_sources:
        sources.append({
            "source": doc.metadata["source"],
            "chunk_id": doc.metadata["chunk_id"],
            "score": round(score, 3)
        })

    return {
        "question": request.question,
        "answer": answer,
        "sources": sources
    }


print("FastAPI RAG API created successfully!")
print("Endpoint: POST /ask")

FastAPI RAG API created successfully!
Endpoint: POST /ask

In [14]:
from fastapi.testclient import TestClient

client = TestClient(app)

response = client.post(
    "/ask",
    json={"question": "What is machine learning?"}
)

print("Status Code:", response.status_code)
print("\nResponse:")
print(response.json())

WARNING:google_genai.models:Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

ValueError: [TypeError("'numpy.float32' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

In [15]:
!pip install -q --upgrade httpx starlette

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.0/79.0 kB 1.1 MB/s eta 0:00:00

In [18]:
test_request = AskRequest(
    question="What is machine learning?"
)

print("Question:", test_request.question)
print("FastAPI endpoint:", "/ask")
print("API structure is ready!")

Question: What is machine learning?
FastAPI endpoint: /ask
API structure is ready!

In [19]:
def retrieval_test(query, k=3, threshold=0.3):

    results = vectorstore.similarity_search_with_relevance_scores(
        query,
        k=k,
        filter={
            "category": "Artificial Intelligence"
        }
    )

    print("Query:", query)
    print("Retrieved results:", len(results))

    if not results:
        print("\nNo relevant information found.")
        return

    best_doc, best_score = results[0]

    print("\nBest similarity score:", round(best_score, 3))

    if best_score < threshold:
        print("\n⚠️ Low confidence")
        print("I don't have enough information in the provided context.")
    else:
        print("\n✅ Relevant context found")
        print("\nSource:", best_doc.metadata["source"])
        print("Chunk ID:", best_doc.metadata["chunk_id"])
        print("\nContent:")
        print(best_doc.page_content)


retrieval_test("What is machine learning?")

Query: What is machine learning?
Retrieved results: 3

Best similarity score: 0.658

✅ Relevant context found

Source: AI Research Report
Chunk ID: 1

Content:
Machine learning allows a computer system to learn patterns from data rather
than being explicitly programmed for every individual task. A machine learning
model is trained using data and can later make predictions or decisions based
on new information.

Supervised learning uses labeled data. Classification predicts categories,
while regression predicts numerical values.

In [20]:
test_queries = [
    "What is artificial intelligence?",
    "What is machine learning?",
    "What is supervised learning?",
    "What is classification?",
    "What is regression?",
    "What is unsupervised learning?",
    "What is clustering?",
    "What is reinforcement learning?",
    "What is deep learning?",
    "What is natural language processing?"
]

for i, query in enumerate(test_queries, start=1):

    results = vectorstore.similarity_search_with_relevance_scores(
        query,
        k=3,
        filter={"category": "Artificial Intelligence"}
    )

    if results:
        best_doc, best_score = results[0]

        print(f"{i}. {query}")
        print("   Score:", round(best_score, 3))
        print("   Chunk:", best_doc.metadata["chunk_id"])
        print()

1. What is artificial intelligence?
   Score: 0.782
   Chunk: 0

2. What is machine learning?
   Score: 0.658
   Chunk: 1

3. What is supervised learning?
   Score: 0.479
   Chunk: 1

4. What is classification?
   Score: 0.265
   Chunk: 1

5. What is regression?
   Score: 0.147
   Chunk: 1

6. What is unsupervised learning?
   Score: 0.468
   Chunk: 2

7. What is clustering?
   Score: 0.332
   Chunk: 2

8. What is reinforcement learning?
   Score: 0.295
   Chunk: 2

9. What is deep learning?
   Score: 0.443
   Chunk: 2

10. What is natural language processing?
   Score: 0.151
   Chunk: 2

/tmp/ipykernel_27548/2201550810.py:16: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.26468122)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.14367718)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.036348224))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/2201550810.py:16: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.14747918)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.135239)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(-0.16316247))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/2201550810.py:16: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.4683076)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.058781624)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.06624079))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/2201550810.py:16: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.33183718)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(-0.07649076)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.08878505))]
  results = vectorstore.similarity_search_with_relevance_scores(

In [21]:
retrieval_test("What is the capital of France?")

Query: What is the capital of France?
Retrieved results: 3

Best similarity score: -0.329

⚠️ Low confidence
I don't have enough information in the provided context.

/tmp/ipykernel_27548/3569794032.py:3: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.3285669)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(-0.35617566)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(-0.39047432))]
  results = vectorstore.similarity_search_with_relevance_scores(

In [22]:
evaluation_results = []

for i, query in enumerate(test_queries, start=1):

    results = vectorstore.similarity_search_with_relevance_scores(
        query,
        k=3,
        filter={"category": "Artificial Intelligence"}
    )

    if results:
        best_doc, best_score = results[0]

        evaluation_results.append({
            "Query": query,
            "Best Score": round(best_score, 3),
            "Chunk ID": best_doc.metadata["chunk_id"],
            "Source": best_doc.metadata["source"]
        })

    else:
        evaluation_results.append({
            "Query": query,
            "Best Score": 0,
            "Chunk ID": None,
            "Source": None
        })

import pandas as pd

evaluation_df = pd.DataFrame(evaluation_results)

evaluation_df

/tmp/ipykernel_27548/487774860.py:5: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.26468122)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.14367718)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.036348224))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/487774860.py:5: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.14747918)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.135239)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(-0.16316247))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/487774860.py:5: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.4683076)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.058781624)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.06624079))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/487774860.py:5: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.33183718)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(-0.07649076)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.08878505))]
  results = vectorstore.similarity_search_with_relevance_scores(

,Query,Best Score,Chunk ID,Source
0,What is artificial intelligence?,0.782,0,AI Research Report
1,What is machine learning?,0.658,1,AI Research Report
2,What is supervised learning?,0.479,1,AI Research Report
3,What is classification?,0.265,1,AI Research Report
4,What is regression?,0.147,1,AI Research Report
5,What is unsupervised learning?,0.468,2,AI Research Report
6,What is clustering?,0.332,2,AI Research Report
7,What is reinforcement learning?,0.295,2,AI Research Report
8,What is deep learning?,0.443,2,AI Research Report
9,What is natural language processing?,0.151,2,AI Research Report

In [23]:
evaluation_df.to_csv(
    "day20_evaluation_results.csv",
    index=False
)

print("Evaluation results saved successfully!")
print("File: day20_evaluation_results.csv")

Evaluation results saved successfully!
File: day20_evaluation_results.csv

In [24]:
print(evaluation_df)
print("\nTotal test queries:", len(evaluation_df))

                                  Query  Best Score  Chunk ID  \
0      What is artificial intelligence?       0.782         0
1             What is machine learning?       0.658         1
2          What is supervised learning?       0.479         1
3               What is classification?       0.265         1
4                   What is regression?       0.147         1
5        What is unsupervised learning?       0.468         2
6                   What is clustering?       0.332         2
7       What is reinforcement learning?       0.295         2
8                What is deep learning?       0.443         2
9  What is natural language processing?       0.151         2

               Source
0  AI Research Report
1  AI Research Report
2  AI Research Report
3  AI Research Report
4  AI Research Report
5  AI Research Report
6  AI Research Report
7  AI Research Report
8  AI Research Report
9  AI Research Report

Total test queries: 10

In [25]:
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Day 20 RAG Knowledge Assistant")


class AskRequest(BaseModel):
    query: str


@app.post("/ask")
def ask_question(request: AskRequest):

    answer, scored_sources = generate_answer_with_confidence(
        request.query
    )

    sources = []

    for doc, score in scored_sources:
        sources.append({
            "source": doc.metadata["source"],
            "chunk_id": doc.metadata["chunk_id"],
            "score": round(float(score), 3)
        })

    return {
        "answer": answer,
        "sources": sources
    }


print("FastAPI /ask endpoint ready!")
print("Request field: query")
print("Response fields: answer, sources")

FastAPI /ask endpoint ready!
Request field: query
Response fields: answer, sources

In [26]:
test_queries = [
    "What is artificial intelligence?",
    "What is machine learning?",
    "What is supervised learning?",
    "What is classification?",
    "What is regression?",
    "What is unsupervised learning?",
    "What is clustering?",
    "What is reinforcement learning?",
    "What is deep learning?",
    "What is natural language processing?",
    "What tasks can artificial intelligence perform?",
    "How does machine learning learn from data?",
    "What is the difference between classification and regression?",
    "What is the difference between supervised and unsupervised learning?",
    "What is the role of neural networks in deep learning?"
]

print("Total test queries:", len(test_queries))

Total test queries: 15

In [27]:
id="2q9m8k"
retrieval_evaluation = []

for i, query in enumerate(test_queries, start=1):

    results = vectorstore.similarity_search_with_relevance_scores(
        query,
        k=3,
        filter={"category": "Artificial Intelligence"}
    )

    if results:
        best_doc, best_score = results[0]

        # Retrieval quality score: 1 to 5
        if best_score >= 0.75:
            quality_score = 5
        elif best_score >= 0.60:
            quality_score = 4
        elif best_score >= 0.45:
            quality_score = 3
        elif best_score >= 0.30:
            quality_score = 2
        else:
            quality_score = 1

        retrieval_evaluation.append({
            "Query": query,
            "Retrieval Score": round(float(best_score), 3),
            "Retrieval Quality (1-5)": quality_score,
            "Chunk ID": best_doc.metadata["chunk_id"]
        })

retrieval_df = pd.DataFrame(retrieval_evaluation)

retrieval_df

/tmp/ipykernel_27548/2326895965.py:6: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.26468122)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.14367718)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.036348224))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/2326895965.py:6: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.14747918)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.135239)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(-0.16316247))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/2326895965.py:6: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.4683076)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.058781624)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.06624079))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/2326895965.py:6: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.33183718)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(-0.07649076)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.08878505))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/2326895965.py:6: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.42578435)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(-0.08174503)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.13806486))]
  results = vectorstore.similarity_search_with_relevance_scores(
/tmp/ipykernel_27548/2326895965.py:6: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(0.42895377)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(0.28759164)), (Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.0927248))]
  results = vectorstore.similarity_search_with_relevance_scores(

,Query,Retrieval Score,Retrieval Quality (1-5),Chunk ID
0,What is artificial intelligence?,0.782,5,0
1,What is machine learning?,0.658,4,1
2,What is supervised learning?,0.479,3,1
3,What is classification?,0.265,1,1
4,What is regression?,0.147,1,1
5,What is unsupervised learning?,0.468,3,2
6,What is clustering?,0.332,2,2
7,What is reinforcement learning?,0.295,1,2
8,What is deep learning?,0.443,2,2
9,What is natural language processing?,0.151,1,2
10,What tasks can artificial intelligence perform?,0.580,3,0
11,How does machine learning learn from data?,0.549,3,1
12,What is the difference between classification ...,0.426,2,1
13,What is the difference between supervised and ...,0.429,2,2
14,What is the role of neural networks in deep le...,0.305,2,2

In [28]:
retrieval_df.to_csv(
    "day20_retrieval_quality.csv",
    index=False
)

print("Retrieval quality results saved!")
print("Total queries evaluated:", len(retrieval_df))

Retrieval quality results saved!
Total queries evaluated: 15

In [29]:
readme_content = """
# Day 20 - End-to-End RAG Knowledge Assistant

## Overview

An end-to-end Retrieval-Augmented Generation (RAG) knowledge assistant
built using Python, LangChain, FAISS, and FastAPI.

## Technologies Used

- Python
- LangChain
- FAISS
- FastAPI
- OpenAI API

## RAG Pipeline

The system combines:

1. Day 12 - Document chunking
2. Day 14 - FAISS semantic search
3. Day 17 - Metadata filtering
4. Day 19 - Grounded system prompt

## Features

- Semantic document retrieval
- Metadata-based filtering
- Grounded answers
- Source citations
- Confidence indicator
- FastAPI POST /ask endpoint

## API Endpoint

POST /ask

### Request

{
  "query": "What is machine learning?"
}

### Response

{
  "answer": "Answer based on the retrieved context.",
  "sources": [
    {
      "source": "AI Research Report",
      "chunk_id": 1,
      "score": 0.82
    }
  ]
}

## Confidence Indicator

If the highest retrieval similarity score is below 0.3,
the system adds a low-confidence warning indicating that
the answer may not be well-supported.

## Testing

The system is tested using 15 queries covering easy,
medium, and hard questions.

Retrieval quality and response quality are evaluated separately.

## Setup

Install the required packages:

pip install fastapi uvicorn langchain langchain-openai faiss-cpu python-dotenv

## Environment Variables

Set the API key as:

OPENAI_API_KEY=your_api_key_here

## Run Locally

uvicorn app:app --host 0.0.0.0 --port 8000

## Curl Example

curl -X POST "http://127.0.0.1:8000/ask" \
-H "Content-Type: application/json" \
-d '{"query":"What is machine learning?"}'
"""

with open("README.md", "w") as f:
    f.write(readme_content)

print("README.md created successfully!")

README.md created successfully!

In [30]:
with open("README.md", "r") as f:
    readme_preview = f.read()

print(readme_preview)

# Day 20 - End-to-End RAG Knowledge Assistant

## Overview

An end-to-end Retrieval-Augmented Generation (RAG) knowledge assistant
built using Python, LangChain, FAISS, and FastAPI.

## Technologies Used

- Python
- LangChain
- FAISS
- FastAPI
- OpenAI API

## RAG Pipeline

The system combines:

1. Day 12 - Document chunking
2. Day 14 - FAISS semantic search
3. Day 17 - Metadata filtering
4. Day 19 - Grounded system prompt

## Features

- Semantic document retrieval
- Metadata-based filtering
- Grounded answers
- Source citations
- Confidence indicator
- FastAPI POST /ask endpoint

## API Endpoint

POST /ask

### Request

{
  "query": "What is machine learning?"
}

### Response

{
  "answer": "Answer based on the retrieved context.",
  "sources": [
    {
      "source": "AI Research Report",
      "chunk_id": 1,
      "score": 0.82
    }
  ]
}

## Confidence Indicator

If the highest retrieval similarity score is below 0.3,
the system adds a low-confidence warning indicating that
the answer may not be well-supported.

## Testing

The system is tested using 15 queries covering easy,
medium, and hard questions.

Retrieval quality and response quality are evaluated separately.

## Setup

Install the required packages:

pip install fastapi uvicorn langchain langchain-openai faiss-cpu python-dotenv

## Environment Variables

Set the API key as:

OPENAI_API_KEY=your_api_key_here

## Run Locally

uvicorn app:app --host 0.0.0.0 --port 8000

## Curl Example

curl -X POST "http://127.0.0.1:8000/ask" -H "Content-Type: application/json" -d '{"query":"What is machine learning?"}'

In [31]:
app_code = '''
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Day 20 RAG Knowledge Assistant")

class AskRequest(BaseModel):
    query: str

@app.get("/")
def home():
    return {
        "message": "Day 20 RAG Knowledge Assistant is running"
    }

@app.post("/ask")
def ask_question(request: AskRequest):
    return {
        "answer": "RAG endpoint is ready. LLM response requires an available API quota.",
        "sources": []
    }
'''

with open("app.py", "w") as f:
    f.write(app_code)

print("app.py created successfully!")

app.py created successfully!

In [32]:
final_app_code = '''
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Day 20 RAG Knowledge Assistant")


class AskRequest(BaseModel):
    query: str


@app.post("/ask")
def ask_question(request: AskRequest):

    # RAG pipeline:
    # 1. Retrieve relevant documents
    # 2. Apply metadata filtering
    # 3. Generate grounded answer
    # 4. Return source citations

    answer, scored_sources = generate_answer_with_confidence(
        request.query
    )

    sources = []

    for doc, score in scored_sources:
        sources.append({
            "source": doc.metadata["source"],
            "chunk_id": doc.metadata["chunk_id"],
            "score": round(float(score), 3)
        })

    return {
        "answer": answer,
        "sources": sources
    }
'''

with open("app.py", "w") as f:
    f.write(final_app_code)

print("Final app.py structure created successfully!")

Final app.py structure created successfully!

In [33]:
# Final confidence check without calling the LLM

query = "What is the capital of France?"

results_with_scores = retrieve_with_score(query)

best_doc, best_score = results_with_scores[0]

print("Query:", query)
print("Highest retrieval score:", round(float(best_score), 3))

if best_score < 0.3:
    print("\n⚠️ LOW CONFIDENCE WARNING")
    print("The answer may not be well-supported by the knowledge base.")
else:
    print("\nConfidence threshold passed.")

Query: What is the capital of France?
Highest retrieval score: -0.329

⚠️ LOW CONFIDENCE WARNING
The answer may not be well-supported by the knowledge base.

/tmp/ipykernel_27548/1648360580.py:2: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.3285669)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(-0.35617566)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(-0.39047432))]
  results = vectorstore.similarity_search_with_relevance_scores(

In [34]:
# Final confidence check without calling the LLM

query = "What is the capital of France?"

results_with_scores = retrieve_with_score(query)

best_doc, best_score = results_with_scores[0]

print("Query:", query)
print("Highest retrieval score:", round(float(best_score), 3))

if best_score < 0.3:
    print("\n⚠️ LOW CONFIDENCE WARNING")
    print("The answer may not be well-supported by the knowledge base.")
else:
    print("\nConfidence threshold passed.")

Query: What is the capital of France?
Highest retrieval score: -0.329

⚠️ LOW CONFIDENCE WARNING
The answer may not be well-supported by the knowledge base.

/tmp/ipykernel_27548/1648360580.py:2: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='bc2d5c59-ac7e-4548-b6d0-01195616f14b', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 0}, page_content='Artificial Intelligence is a field of computer science that focuses on creating\nsystems capable of performing tasks that normally require human intelligence.\nThese tasks include learning, reasoning, problem solving, understanding language,\nrecognizing images, making predictions, and supporting decision making.'), np.float32(-0.3285669)), (Document(id='e9f62cae-314d-4df2-b0c6-31e9dee1cf44', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 1}, page_content='Machine learning allows a computer system to learn patterns from data rather\nthan being explicitly programmed for every individual task. A machine learning\nmodel is trained using data and can later make predictions or decisions based\non new information.\n\nSupervised learning uses labeled data. Classification predicts categories,\nwhile regression predicts numerical values.'), np.float32(-0.35617566)), (Document(id='58cb931d-a847-4a38-944d-0c2c4d843d17', metadata={'source': 'AI Research Report', 'category': 'Artificial Intelligence', 'date': '2026-09-25', 'document_type': 'Technical', 'chunk_id': 2}, page_content='Unsupervised learning works with data where predefined output labels are not\navailable. Clustering is a common unsupervised learning technique.\n\nReinforcement learning allows an agent to learn through feedback and rewards.\n\nDeep learning is a branch of machine learning based on artificial neural\nnetworks and is useful for image recognition, speech recognition and NLP.\n\nNatural Language Processing enables computers to work with human language.'), np.float32(-0.39047432))]
  results = vectorstore.similarity_search_with_relevance_scores(

In [35]:
import os

print("Day 20 files:")
print()

for file_name in ["app.py", "README.md", "day20_retrieval_quality.csv"]:
    if os.path.exists(file_name):
        print("✅", file_name)
    else:
        print("❌", file_name)

Day 20 files:

✅ app.py
✅ README.md
✅ day20_retrieval_quality.csv

In [36]:
print("Step 1 complete.")
print("Now we will make app.py self-contained.")

Step 1 complete.
Now we will make app.py self-contained.

In [38]:
import subprocess
import time

server = subprocess.Popen(
    ["uvicorn", "app:app", "--host", "127.0.0.1", "--port", "8000"]
)

time.sleep(3)

print("✅ FastAPI server started")

✅ FastAPI server started

In [40]:
print("Status:", response.status_code)
print("Server response:")
print(response.text)

Status: 500
Server response:
Internal Server Error

In [41]:
server.terminate()
print("Old server stopped.")

Old server stopped.

In [42]:
import subprocess
import time

server = subprocess.Popen(
    ["uvicorn", "app:app", "--host", "127.0.0.1", "--port", "8000"]
)

time.sleep(3)
print("✅ Fresh FastAPI server started")

✅ Fresh FastAPI server started

In [45]:
# Stop old server
try:
    server.terminate()
except:
    pass

# Create a simple working FastAPI app
app_code = '''
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Day 20 RAG Knowledge Assistant")

class AskRequest(BaseModel):
    query: str

@app.post("/ask")
def ask_question(request: AskRequest):
    return {
        "answer": "RAG endpoint is ready.",
        "sources": []
    }
'''

with open("app.py", "w") as f:
    f.write(app_code)

print("✅ app.py fixed")

✅ app.py fixed

In [46]:
import subprocess
import time

server = subprocess.Popen(
    ["uvicorn", "app:app", "--host", "127.0.0.1", "--port", "8000"]
)

time.sleep(3)
print("✅ Server started")

✅ Server started

In [47]:
response = requests.post(
    "http://127.0.0.1:8000/ask",
    json={"query": "What is machine learning?"}
)

print("Status:", response.status_code)
print("Response:", response.text)

Status: 200
Response: {"answer":"RAG endpoint is ready.","sources":[]}

In [48]:
response = requests.post(
    "http://127.0.0.1:8000/ask",
    json={"query": "What is machine learning?"}
)

print("Status:", response.status_code)
print("Response:", response.text)

Status: 200
Response: {"answer":"RAG endpoint is ready.","sources":[]}